### ISSUE TITLE
网页翻译的结果能设置样式吗？

### ISSUE THREAD

**Issue by allen668261** [chunibyocola/sc-translator-crx#101]
网页翻译的结果能设置样式吗？ 比如添加文字颜色 或者背景色 改变字体大小？

**Comment by chunibyocola** [comment]
目前是做不到的，而且也没有必要。因为网页背景文字并不是保持不变的，各个网站都会为了保证用户浏览体验和网站特色而决定一个更适合的样式，在这种背景下保持原来的样式才是最佳的做法。当然你也可以通过一些扩展或脚本来人工加入样式，比如“油猴”的自定义脚本。
