### ISSUE TITLE
[功能请求]翻译面板的朗读引擎使用与翻译源不同的朗读引擎

### ISSUE THREAD

**Issue by song2daodao** [chunibyocola/sc-translator-crx#106]
目前扩展的设置界面能分别把朗读源设置成bing，翻译源设成百度。但是用百度翻译时点击翻译面板内的朗读小图标，用的貌似就不是bing的朗读引擎，而是百度的。只有单独选文字朗读才用的bing的。

要是翻译面板的朗读引擎也能单独设置就好了，而不是和翻译源的一致，扩展很好用，谢谢作者

**Comment by chunibyocola** [comment]
之后会朗读源下方增加新的“在其他翻译源中使用此朗读源”选项。

感谢建议。
