### ISSUE TITLE
[bug] reddit 登录后页面滚动会出问题

### ISSUE THREAD

**Issue by hxse** [chunibyocola/sc-translator-crx#107]
示例: https://www.reddit.com/r/Anki/
登录后, 点击翻译当前页面, 出现翻译结果, 然后滚轮往下滚一会儿, 就会弹回到界面顶部, 然后翻译结果也会消失
不知道是什么原因, 但是退出登录后, 发现就正常了
没有开启"翻译动态生成的内容"

**Comment by chunibyocola** [comment]
每个网站都会有自己的动态更新内容的策略，像 reddit 这种的是会直接刷新整个页面的更新策略如果不启用“翻译动态生成的内容”的话就会出现翻译结果消失的情况。还有更严格的不允许修改内容的网站比如 facebook 和一些采用了某些库的个人博客，在这些网站甚至做不到网页翻译（浏览器自带的网页翻译也同样不可用）。

针对这些情况是无法修复的，唯一能做的就是启用“翻译动态生成的内容”后看看能不能达到一种能用的状态。所以这个 issue 就先关闭了，有其他问题可以在此 issue 下回复。

**Comment by hxse** [comment]
@chunibyocola 启动动态翻译后可以翻译, 但是滚动到页面底部后还是会弹回, 我发现这是reddit的问题, 用edge自带的页面翻译也会有这个问题
https://www.reddit.com/r/chrome/comments/xtb5ic/using_google_translate_makes_it_impossible_to/
