### ISSUE TITLE
http 429

### ISSUE THREAD

**Issue by zachackr** [chunibyocola/sc-translator-crx#11]
SC 没法用了，我不确定是我自己的网络环境问题，还是插件请求过于频繁，被限制住了。
![image](https://user-images.githubusercontent.com/74852229/120289089-80e0f500-c2f3-11eb-8841-cbc01713d8e1.png)

![image](https://user-images.githubusercontent.com/74852229/120289159-935b2e80-c2f3-11eb-905e-e0f5e5c0dea2.png)

![image](https://user-images.githubusercontent.com/74852229/120289205-a110b400-c2f3-11eb-95ab-722850941bf7.png)

![image](https://user-images.githubusercontent.com/74852229/120289245-ac63df80-c2f3-11eb-8f8c-7dc634ea2aca.png)

**Comment by chunibyocola** [comment]
你好
Google 的大概是太频繁了，一旦触发了就需要等待半小时；
Bing 的接口更新了，我已经修复好了，预计这周五或者下周一发布；
Mojidict 只接受中日文单词和一些句子；
百度的话大概点击重试就可以了，有几率在第一次请求就发生，频繁发生我还没试过。请问百度翻译是属于哪种情况呢？

**Comment by zachackr** [comment]
> 你好
> Google 的大概是太频繁了，一旦触发了就需要等待半小时；
> Bing 的接口更新了，我已经修复好了，预计这周五或者下周一发布；
> Mojidict 只接受中日文单词和一些句子；
> 百度的话大概点击重试就可以了，有几率在第一次请求就发生，频繁发生我还没试过。请问百度翻译是属于哪种情况呢？

百度第一次请求就发生了

**Comment by chunibyocola** [comment]
点击重试之后呢，还会发生吗？如果没有发生的话你可以先默认使用百度翻译。等到 Google 翻译恢复后再使用 Google 翻译。

**Comment by zachackr** [comment]
> 点击重试之后呢，还会发生吗？如果没有发生的话你可以先默认使用百度翻译。等到 Google 翻译恢复后再使用 Google 翻译。

百度在多次重试之后，有一定概率会正常工作。试了几次，分别在重试5次，2次，7次，27次后正常工作。。

**Comment by chunibyocola** [comment]
大于一次，这是我没有想到的😂看来我需要特别注意一下百度翻译的这个问题。
