### ISSUE TITLE
[功能请求]选择网页翻译译文的样式的功能

### ISSUE THREAD

**Issue by xxnuo** [chunibyocola/sc-translator-crx#110]
希望可以添加自行选择网页翻译译文的样式的功能，效果类似下面的绿色文字
![图片](https://user-images.githubusercontent.com/54252779/210196630-bb224561-8ad8-4835-9558-6fa66e2ad7ce.png)

我看主题里有自定义样式的功能，但是网页翻译的译文好像没有固定的类名？

**Comment by chunibyocola** [comment]
我想了这个问题一段时间，我觉得不应该实现。

自定义样式的范围是扩展内部，而网页翻译其实作用的是外部，是不应该涉及到的，这方面应该由其他专门面向页面样式的扩展来做。

> 网页翻译的译文好像没有固定的类名？

没有类名是因为不想产生额外的样式冲突问题。

> 效果类似下面的绿色文字

这种固定颜色是不应该实现的，只应该从字体样式下手，因为如果目标网页是绿色背景的话这种方式会起到反作用。

非常感谢你提出的建议。

**Comment by xxnuo** [comment]
好的，感谢回复
