### ISSUE TITLE
bing翻译失效

### ISSUE THREAD

**Issue by charon979** [chunibyocola/sc-translator-crx#112]
![1673587129499](https://user-images.githubusercontent.com/116360738/212243257-af65ebe2-2374-4cf9-bbd7-3606fed2ae26.jpg)

**Comment by chunibyocola** [comment]
Bing 翻译引擎做了一些改变，这些改变导致了翻译错误，预计在下周一发布新的版本去修复这个问题，现在可以先使用其它翻译引擎代替。

**Comment by charon979** [comment]
好的，辛苦啦~

**Comment by chunibyocola** [comment]
新版本 v4.7.1 已经发布，目前在 Firefox 扩展商店中已经审核通过， Chrome 和 Edge 的扩展商店需要一定的审核时间。

感谢你报告此问题。
