### ISSUE TITLE
Can't change keyboard shortcuts in settings

### ISSUE THREAD

**Issue by wojtulace** [chunibyocola/sc-translator-crx#114]
'Customize here' button does nothing.

**Comment by chunibyocola** [comment]
In Firefox, there is no way to direct to the keyboard shortcut customization page, so this button is not working. You have to follow the Firefox way to customize.

The steps below:
1. Open addons page (Ctrl+Shift+A)
2. Click the setting icon button
3. Click "Manage keyboard shortcut settings"

**Comment by wojtulace** [comment]
Thanks
