### ISSUE TITLE
你好，反馈一个Bug！希望能够修复！

### ISSUE THREAD

**Issue by cc19264997** [chunibyocola/sc-translator-crx#115]
划词翻译在油管直播聊天（图1）选中文字无法翻译，在评论区（图2）或其他网站正常，希望修复

![01](https://user-images.githubusercontent.com/25716656/216514925-5296afef-2a03-4875-9ed3-03f59401eff2.png)

![02](https://user-images.githubusercontent.com/25716656/216514930-deaa7345-2cc0-4d5c-93b7-bdb5580cd5ec.png)

**Comment by chunibyocola** [comment]
这个问题是因为这个网站使用了 iframe，而现在扩展不会在 iframe 里注入脚本。

至于为什么不注入是因为没办法做到完全不影响这类网页的正常运作，在一些网站会监听 iframe 发送过来的信息，但是不会做过滤，从而导致了当用户尝试在 iframe 中选择文本时会导致页面错误，这是我不想看到的，这个问题也是非常普遍的。
