### ISSUE TITLE
你好，百度和必应的翻译源失效了

### ISSUE THREAD

**Issue by cc19264997** [chunibyocola/sc-translator-crx#117]
如图   是失效了吗？

![01](https://user-images.githubusercontent.com/25716656/218390284-0b36e8a6-a271-4464-a22b-67bab2b57dff.png)

**Comment by cc19264997** [comment]
![1](https://user-images.githubusercontent.com/25716656/218389907-d5063162-e7c4-49d4-8909-cd733fc5a370.png)

关了VPN是这样，就剩百度了。。

**Comment by chunibyocola** [comment]
Bing 修复过了，你可以更新一下版本。

百度的话你试试翻译其他文字，如果还是一样的话估计是 Cookie 问题，可以试试先访问百度官网后再试试，我这边是全部都正常的。

所以 issue 先关闭，有问题可以继续在下方回复。

**Comment by cc19264997** [comment]
郁闷，还是不行。。(可可翻译 v4.7.1)  再一个刚看QQ邮箱选中文字不会出按钮。。
![微信图片_20230213150112](https://user-images.githubusercontent.com/25716656/218392066-e4572461-20e8-41b1-bf04-02ce3cb4c2bf.png)

**Comment by chunibyocola** [comment]
那就试试清除`fanyi.baidu.com`的所有缓存后再试试吧。

> 再一个刚看QQ邮箱选中文字不会出按钮。。

选取在 iframe 里的文字不会触发弹出按钮，这种情况下只能使用右键。
