### ISSUE TITLE
希望翻译展示里加一个把原文去掉的选项

### ISSUE THREAD

**Issue by ifeif** [chunibyocola/sc-translator-crx#120]
翻译结果里的原文用处不大
希望翻译展示里加一个把原文去掉的选项
![image](https://user-images.githubusercontent.com/36729028/221555163-7691b07c-02d4-4f91-8975-a98ef32b137c.png)
![image](https://user-images.githubusercontent.com/36729028/221554578-f48d636f-bc9e-4b15-a2c5-c2e62f847ff6.png)

**Comment by chunibyocola** [comment]
这是需要的，你可以通过自定义样式的方式去掉这一段，或者使用“复数翻译模式”，在这个模式下不会展示原文。

**Comment by ifeif** [comment]
> 这是需要的，你可以通过自定义样式的方式去掉这一段，或者使用"复数翻译模式"，在这个模式下不会展示原文。

那么如何通过自定义样式去掉这一段原文？

**Comment by ifeif** [comment]
![image](https://user-images.githubusercontent.com/36729028/227140781-51ba75e8-2c8e-49dd-ad1d-e2d141390ba6.png)

**Comment by ifeif** [comment]
@chunibyocola

**Comment by chunibyocola** [comment]
目前好像自定义样式的方式不能完美做到隐藏原文（因为不同源显示的数据是不固定的），但是下个版本会去掉这个原文，改成“复数翻译模式”那样。
