### ISSUE TITLE
Persist / share configuration

### ISSUE THREAD

**Issue by mrsimpson** [chunibyocola/sc-translator-crx#122]
I'd like to pre-configure sc-translate for co-workers so they don't have to perform all the configuration by themselves – and 
sc-translator features a lot of configuration options ❤️ 

Is there an option to down / upload the settings?

**Comment by chunibyocola** [comment]
There is a section "Sync settings", you can see there can export/import settings, I think this can fit your requirement.

**Comment by mrsimpson** [comment]
Ahh! That was too ... obvious 😬 
Thanks
