### ISSUE TITLE
Exclude built-in translation engines

### ISSUE THREAD

**Issue by mrsimpson** [chunibyocola/sc-translator-crx#123]
I'm currently evaluating the usage of you wonderful extension in a corporate context.
As I implemented a custom translation resource which is compliant to our privacy requirements, I'd like to disable the in-built translation engines. Is there such a setting?

**Comment by chunibyocola** [comment]
> I'd like to disable the in-built translation engines. Is there such a setting?

There is no such an option.

**Comment by mrsimpson** [comment]
Would you accept a PR for that? I'd like to avoid forking the extension
