### ISSUE TITLE
Original text overlay hides behind other element of the page translated

### ISSUE THREAD

**Issue by mrsimpson** [chunibyocola/sc-translator-crx#125]
when translating a web page which itself contains element with a `z-index` > 0, the original text cannot be read as it hides behind it.

Sample
<img width="865" alt="Bildschirm­foto 2023-03-06 um 14 46 59" src="https://user-images.githubusercontent.com/17176678/223155922-7481e049-3fb4-4fdd-be0e-1d6ba1f77452.png">

**Comment by chunibyocola** [comment]
Oh, I just misunderstand before.

I test a little, I think the z-index should be set at max.

Thanks for you report!
