### ISSUE TITLE
Translation loses whitespaces

### ISSUE THREAD

**Issue by mrsimpson** [chunibyocola/sc-translator-crx#128]
When utilizing a custom (DeepL based) web page translation engine, translations are being stripped their whitespaces.
This has the effect, that text nodes which are not containers (like `<span>`) and are embedded in a paragraph are being clubbed together.

As you need a custom translation provider with this behaviour, I recorded a small screencast to illustrate the problem

https://user-images.githubusercontent.com/17176678/223773721-e2c58599-6eac-40ab-85ff-b8cad001358e.mov

Do you think this is to be fixed in the translation provider or shall the extension support a relaxed handling of un-padded translations?

**Comment by chunibyocola** [comment]
There are no whitespaces get lost in request body, so it shoulds be handled by server side. Other languages like Chinese, Japanese are no whitespaces in sentence, adding whitespaces in client side is not reasonable.

**Comment by mrsimpson** [comment]
After writing the issue I also thought the same. I implemented a fix in the translation provider already.
