### ISSUE TITLE
如何添加Deepl翻译引擎？

### ISSUE THREAD

**Issue by e-Shaun** [chunibyocola/sc-translator-crx#129]
看到Deepl有免费的API，但是不知道怎么把Deepl添加到[sc-translator-crx]里面

**Comment by chunibyocola** [comment]
使用[自定义翻译源](https://github.com/chunibyocola/sc-translator-crx/discussions/31)的功能在本地或云上部署一个翻译服务。

下个版本**可能**会添加 DeepL 翻译源。

**Comment by stvv0000** [comment]
> 使用[自定义翻译源](https://github.com/chunibyocola/sc-translator-crx/discussions/31)的功能在本地或云上部署一个翻译服务。
> 
> 下个版本**可能**会添加 DeepL 翻译源。

waiting for deepl!
