### ISSUE TITLE
Google page translator loses spaces at the end of a sentence.

### ISSUE THREAD

**Issue by Dook1** [chunibyocola/sc-translator-crx#132]
Example:   "First. Second." -> "First.Second."
Microsoft translator doesn't have this problem.

**Comment by chunibyocola** [comment]
No such situation was observed. Can you provide more infomation like websites, GIFs or images? Thank you.

**Comment by Dook1** [comment]
[](url)

**Comment by Dook1** [comment]
![Screenshot 2023-04-13 at 13-36-49 Google page translator loses spaces at the end of a sentence  · Issue #132 · chunibyocola_sc-translator-crx](https://user-images.githubusercontent.com/18645441/231734877-1b5e3309-382a-4cb1-bbca-b3cf07504f24.png)
![Screenshot 2023-04-13 at 13-38-10 Google page translator loses spaces at the end of a sentence  · Issue #132 · chunibyocola_sc-translator-crx](https://user-images.githubusercontent.com/18645441/231734937-154665ff-effd-4ebf-b20d-b7dc99176516.png)
![Screenshot 2023-04-13 at 13-39-32 Google page translator loses spaces at the end of a sentence  · Issue #132 · chunibyocola_sc-translator-crx](https://user-images.githubusercontent.com/18645441/231734966-de7097d1-cd4c-4959-acd7-756fda905b88.png)

**Comment by chunibyocola** [comment]
Thanks for providing more information.

I have figured out why it is happening and I have fixed it. But the fix still need to be tested in more situations.

Thank you for reporting!
