### ISSUE TITLE
朗读功能好像用不了

### ISSUE THREAD

**Issue by prettywinter** [chunibyocola/sc-translator-crx#133]
您好，感谢这么好的插件。
最近发现了一个问题，我使用的 Bing 翻译、朗读服务，但是现在朗读功能无效，是微软朗读的 API 改了？

**Comment by chunibyocola** [comment]
你好。

> 最近发现了一个问题，我使用的 Bing 翻译、朗读服务，但是现在朗读功能无效，是微软朗读的 API 改了？

是的，这个问题已经修复了，在下个版本中会包含这个修复。

感谢你报告这个问题。
