### ISSUE TITLE
这些评论界面的都不能翻译吗？ 是动态吗？还是独立界面原因呢

### ISSUE THREAD

**Issue by yangchen158158** [chunibyocola/sc-translator-crx#134]
https://www.foxnews.com/tech/flashback-stephen-hawking-warned-ai-end-human-race-years-leading-death
类似这些评论界面上面，都不能点网页翻译成功的！

**Comment by chunibyocola** [comment]
这个网站的评论部分做了特殊的处理，不被允许更改。我尝试了官方的谷歌翻译也同样翻译不了。
