### ISSUE TITLE
[Feature] Pre-configure the extension at build time

### ISSUE THREAD

**Issue by mrsimpson** [chunibyocola/sc-translator-crx#136]
Though the extension is very much configurable (with custom CSS, custom translate resources, languages, ...), not every user is able to do this.
In our company, we'd therefore like to pre-configure it before rolling it our to all employees.
As you already have the option to ex- and import settings, it sounds at least possible to either
- Change the default of those settings at build time
- If a `defaults.sctranslator` file was found in the root of the extension, read them at runtime.

**Comment by chunibyocola** [comment]
> Change the default of those settings at build time
> If a `defaults.sctranslator` file was found in the root of the extension, read them at runtime.

It needs the CRX file in store that is modifiable, but it is impossible, and it is a dangerous move, I will not do that.

If you want to modify the CRX file to make it possible, there is a simple way, just write a background script and add it into `manifest.json`. And If you don't want the default translation sources show out, just hide every translation selectors through CSS customization and block options page.

**Comment by mrsimpson** [comment]
Thanks for the idea with the background script.
Still, I think you misunderstood my intention:
I'd wish to provide defaults when executing `yarn build`. How would this be a dangerous move?
