### ISSUE TITLE
[Feature] Chose default translation engine per URL

### ISSUE THREAD

**Issue by mrsimpson** [chunibyocola/sc-translator-crx#137]
## Motivation

Some translation engines provide better results for dedicated domains.
E. g. corporate domains could use a trained translation engine where the public internet is being translated with Google or Bing.

## Ideas for implementation
When configuring the translation providers, multiple sources could be configured. Each source could be optionally attached a RegEx which specifies when this engine shall be used.
The first engine in the list matching the expression would then be used.

**Comment by chunibyocola** [comment]
> Some translation engines provide better results for dedicated domains.
E. g. corporate domains could use a trained translation engine where the public internet is being translated with Google or Bing.

It is no need to hide the default translation sources. A more appropriate way ref #136 .

**Comment by mrsimpson** [comment]
I don't want to hide default translation resources. This can be done by CSS, that's fine.

What I'd wish is

*.foo.bar -> custom translation source 1
*.foo -> custom translation source 2
Other URLs -> Google

I don't quite get how a background script would enable switching the translation source.
Of course, I could manipulate network requests with [`declarativeNetRequest`](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/), but this would essentially mean duplication of a lot of code.

Can you elaborate a bit?
