### ISSUE TITLE
开启“检测到段落时换行展示译文”后，似乎GitHub有些地方会复读

### ISSUE THREAD

**Issue by qznfbnj** [chunibyocola/sc-translator-crx#138]
截图都是“显示译文”方式
## 关闭“检测到段落时换行展示译文”
![image](https://github.com/chunibyocola/sc-translator-crx/assets/100760086/e8cda358-17d3-4899-a625-2b398de94fa1)
![image](https://github.com/chunibyocola/sc-translator-crx/assets/100760086/d4a70865-c546-4732-b5ae-31cac8038086)

## 打开“检测到段落时换行展示译文”
![image](https://github.com/chunibyocola/sc-translator-crx/assets/100760086/c3abdcc0-3210-4450-9f84-1398c42126c1)
![image](https://github.com/chunibyocola/sc-translator-crx/assets/100760086/e3855a18-6f7c-4728-95ac-5d88db9b0565)
---
![image](https://github.com/chunibyocola/sc-translator-crx/assets/100760086/c3b9c273-af40-494b-acc5-611a093f72af)
---
![image](https://github.com/chunibyocola/sc-translator-crx/assets/100760086/68b033d6-934f-40e2-8d63-2d3b3d2dded2)

**Comment by chunibyocola** [comment]
我尝试了一下，确实复现了。

问题的发生是 GitHub 的下面这一段 CSS 导致的：

```CSS
.d-inline-block {
    display: inline-block !important;
}
```

确实是疏忽了这一点😂，在 `style="display: none"` 加上 `!important` 就可以解决了，感谢你提交的这个 Bug
