### ISSUE TITLE
[功能请求]  翻译动态生成的内容 的黑名单

### ISSUE THREAD

**Issue by qznfbnj** [chunibyocola/sc-translator-crx#140]
好吧，关闭 翻译动态生成的内容 后，仍然能连续复现崩溃

**Comment by chunibyocola** [comment]
我这几天还没有去仔细考虑这个问题，只是大概地想了一下功能的必要性和能否修复这个问题。

但这个问题应该是无法修复的，我没有使用 Discord，但根据报错信息我判断这应该与 Discord 的实现有关，使用浏览器自带的网页翻译大概也会有这个问题。
