### ISSUE TITLE
如何使用文本预处理，不翻译某些术语

### ISSUE THREAD

**Issue by SendorWang** [chunibyocola/sc-translator-crx#141]
如题所示

**Comment by chunibyocola** [comment]
求助的话不太应该发在这个区域里，所以先关闭，后续依然可以在这个 issue 里提问。

能举个例子吗补充说明吗。

**Comment by SendorWang** [comment]
感谢您的快速回复，大大超过我的预期。
我用可可翻译web页面：
原文：The database schema - not required if your database does not use schemas, or if there is a default schema. 
我得到的译文：数据库架构 - 如果您的数据库不使用架构，或者有默认架构，则不需要。
我希望的译文：数据库schema - 如果您的数据库不使用schema，或者有默认schema，则不需要。

我觉得可可的翻译是恰当的。但是我希望我能够用我个性化的设置，得到我想要的译文。

顺便问下，求助应该在哪里？

再次感谢!

**Comment by chunibyocola** [comment]
文本预处理不能处理网页翻译的文本，目前也做不到这种操作。

页面翻译的确可以做到不翻译句子中的一部分文本，但是你可以自行写一个脚本，把符合的文本都用`code`标签包起来，或者`span`标签包起来并加上`class="notranslate"`，但是这种方法相当于打断了句子结构，翻译源不一定能处理好。

如果可能的话，你可以通过自定义页面翻译源来处理，这是最优的一种方式。

**Comment by SendorWang** [comment]
非常感谢
