### ISSUE TITLE
Text formatting is lost

### ISSUE THREAD

**Issue by Dook1** [chunibyocola/sc-translator-crx#143]
Original text:
![Screenshot 2023-08-11 at 12-30-14 1267027 - meta Page CSP should not apply to content inserted by content scripts (V2 issue)](https://github.com/chunibyocola/sc-translator-crx/assets/18645441/05271aee-47a4-4c95-a266-fe13840f305a)
Translated text:
![Screenshot 2023-08-11 at 12-29-44 1267027 - meta Page CSP should not apply to content inserted by content scripts (V2 issue)](https://github.com/chunibyocola/sc-translator-crx/assets/18645441/6f6d5e78-87be-456f-a2c9-17703ab9bc67)

**Comment by chunibyocola** [comment]
This situation get observed when you are using Google translation source, but it is normal in using Bing translation source.

I will fix it as soon as possible.

Thanks for your report!
