### ISSUE TITLE
[Recommend] If the original text language is the same as the target language, the translation should not be displayed

### ISSUE THREAD

**Issue by hs01a** [chunibyocola/sc-translator-crx#144]
你好，亲爱的软件开发者。首先说说这个翻译插件，实在太棒了。其次希望软件有一个改进：比如翻译为简体中文，选择了[原文+译文]选项后，会在简体中文之后重复显示，（原文+原文）。
建议不要这样，或者加入去除的选项。
Hello, dear software developers. First of all, let me talk about this translation plugin, it is really great. Secondly, I hope that the software will have an improvement: For example, when translated into Simplified Chinese, after selecting the [Original + Translation] option, it will be displayed repeatedly after Simplified Chinese, (Original + Original).
It is recommended not to do this, or add an option to remove it.（google translate）

**Comment by hs01a** [comment]
嗯，发现开发者是中国人或华人。

**Comment by chunibyocola** [comment]
你好，感谢你的建议！

我会在下个版本中在“增强展示”的“原文 + 译文”下加入新的选项“当文本语言与目标语言相同时不展示译文”。

**Comment by hs01a** [comment]
谢谢你的回应。期待你之后的版本。你这个插件真的很好用，翻译迅速，界面和翻译的方式也好看与实用。就是用户相对少了点，不应该（从火狐、edge来看、chrome的不知道）(其实用户也不少了，而评分又高)。

另外：本人其它一些建议。

1.关于设置页。看起来混乱，你这个设置页一些词句 很多很难看懂。如 一些项目用语 建议可改为不限于：全局设置（或基本设置）、网页全文翻译（设置）、划词翻译弹窗（设置）、基它设置、等等。（一眼能看懂很重要。）
其实也不用那多个自定义选项的，可酌情删减和优化。如：我第一次建议的那个情况，直接就是："若原文是翻译的目标语言 不作翻译"就是了，不用加选项。

2.关于“原文+译文”，最好原文与译文空出一或两格。或可自定义译文文字颜色。

3.“激活网页翻译后直接翻译”选项最好默认是勾选的。因为会有一些 第一次用这插件的 或不知道有此项的人 会以为这插件不能用。

3.简介可改进下。如：“可可翻译”是一款免费（按：若以后不免费 删除“免费”就是了）迅捷的“网页翻译、划词翻译”的插件。多翻译源。丰富的设定：独立的划词翻译弹窗、自定义主题、快捷键、全网页翻译历史、翻译收藏。

看在你快捷回应我的反馈份上，我就很认真的建议了，虽然对你不一定有用就是了。你对我后面加的建议也不必较真，我是仅建议。

**Comment by chunibyocola** [comment]
> 1.关于设置页。看起来混乱，你这个设置页一些词句 很多很难看懂。

这个是有想要去改善一下结构的，但不是目前优先去做的，也没什么明确的头绪。

> 2.关于“原文+译文”，最好原文与译文空出一或两格。或可自定义译文文字颜色。

这个之前也有用户提过相同的需求，但是我认为不应该在扩展的外部插入额外的样式定义。不过既然被多次提及，我会去增加一个可以改变字体样式的方法，不过不会是自定义样式的方式，而是提供预先提供的样式，比如：字体颜色、外框的样式、外框的颜色。

> 3.“激活网页翻译后直接翻译”选项最好默认是勾选的。因为会有一些 第一次用这插件的 或不知道有此项的人 会以为这插件不能用。

这个状况是存在，我曾经见过一部分用户有相同的问题。这个我也在纠结中，因为使用的 API 并不是自己的，如果再加上这个就有点太过了的感觉，毕竟原本的初衷就只是增强网页翻译的体验，而不是去取代原来的。我会再去纠结一下的。

> 4.简介可改进下。如：“可可翻译”是一款免费（按：若以后不免费 删除“免费”就是了）迅捷的“网页翻译、划词翻译”的插件。多翻译源。丰富的设定：独立的划词翻译弹窗、自定义主题、快捷键、全网页翻译历史、翻译收藏。

这个因为谷歌商店那边有字数限制，所以也是比较头疼的，我认为按目前的也不错。

非常感谢你提供的建议！

**Comment by hs01a** [comment]
谢谢回应。
设置选项一般要简明，让人能快速看明白。
我认为：你这设置页，结构还OK，可先不用去改。让看起来混乱，我认为是很大原因是：用词太笼统了，要让人研究老半天，我相信大部分人看了这插件的设置页都是这样（你可以找周边的人问问），或直接不想了解了。所以只要用词稍改下，就会有很好的改进。
可参考如下：（不完全词句）
“网页翻译”改为→“网页全文翻译”
“独立翻译窗口”→“独立翻译窗口（点击插件图标的弹窗）”
“翻译面板”→“划词翻译弹窗”{重点是要改这个。不摸索 或不从头看到尾 还真不能确定"这个面板"是"哪个面板"}

这样就能让人一下子能了解是设置哪的了。

注：其实我也不知上面的对等关系 是否正确。

以上，仅作建议。

**Comment by chunibyocola** [comment]
你好，

新选项“当文本语言与目标语言相同时不展示译文”与译文样式自定义已经开发完成。“激活网页翻译后直接翻译”这一选项已经被设置为默认开启。

所有的更改将会在 v5.2.0 中启用，目前已经提交审核， Firefox 商店中已经审核完毕。

再次感谢你所提出的所有建议！

**Comment by hs01a** [comment]
谢谢。看了看，“原文+译文”方面，这样改之后 好用太多了。加上译文可加下划线 并可自定义下划线颜色与样式，这样简单 好用 又美观。用来翻译YOUTU观感很好（之前YOUTU“原文+译文”没法看）。
