### ISSUE TITLE
[建议] 增加后台保持运行的选项

### ISSUE THREAD

**Issue by detiam** [chunibyocola/sc-translator-crx#146]
![image](https://github.com/chunibyocola/sc-translator-crx/assets/44510779/84ea9fba-24cb-4f22-aced-0d4c6e885754)
浏览器窗口关了也可以呼出独立翻译窗口

**Comment by chunibyocola** [comment]
如果我没弄错的话，现在这个方法在新版 Chromium 已经不能用了，必须要在浏览器已打开下使用。我自己也试了一下，确实不能使用了。

**Comment by detiam** [comment]
@chunibyocola 不过我在edge浏览器里还能用，好吧
