### ISSUE TITLE
Contextmenu for fast add page to "Automatic translation webpages"

### ISSUE THREAD

**Issue by Dook1** [chunibyocola/sc-translator-crx#148]
Please add contextmenu for fast add page to "Automatic translation webpages"

**Comment by chunibyocola** [comment]
Hello,
I am not sure it is reasonable enough to add a new context menu to handle this kind of move.

1. Add domain name into auto-translate list will not ask extension to translate the current page.
2. Users do the add/remove things that related to auto-translate list often already in page translated state.
3. Users can't clearly recognize that the current page is in auto-translate list.

In my opnion, most users will eventually need to open control bar. Some users might enable the "Not display control bar during first activating" option, but it still just needs one more mouse clicking than do it through context menu.

So, it is why it is not reasonable for me now.
Thanks for your recommending.

**Comment by Dook1** [comment]
It would be convenient if you could do like in Linguist - item in popup menu on browserAction.
