### ISSUE TITLE
无法翻译像 GitHub twitter 这样的网页

### ISSUE THREAD

**Issue by xiaoyuhaoge** [chunibyocola/sc-translator-crx#152]
如图，是不是因为网站策略的原因，但是我使用TWP可以正常翻译GitHub
![IMG_1138](https://github.com/chunibyocola/sc-translator-crx/assets/134502767/50996217-e490-42ca-8125-5047cfee1d84)
![IMG_1136](https://github.com/chunibyocola/sc-translator-crx/assets/134502767/b9eff228-ac94-4b01-a362-a0d53c64114d)

**Comment by chunibyocola** [comment]
这是因为网络请求出问题了，你可以看到第一张图中右下角控制栏中显示`Error: get authorization failed. Retry`，这说明请求翻译服务器的认证失败，在大陆网络中这是很常见的一种状况，这时候需要你点击`Retry`来再次发送认证请求。

**Comment by chunibyocola** [comment]
![image](https://github.com/chunibyocola/sc-translator-crx/assets/46666257/3ca59f0f-d99c-41ed-b15a-1a42e7f0692e)
我这里试到是没有问题的，如果其他网站可以，那 GitHub 就不太可能不可以。

**Comment by chunibyocola** [comment]
如果是 CSP 比较严格的浏览器的话确实有可能，因为 GitHub 的确存在 CSP 限制。
