### ISSUE TITLE
希望文本预处理功能可以对网页翻译生效

### ISSUE THREAD

**Issue by yaodao0yaodao** [chunibyocola/sc-translator-crx#155]
希望文本预处理功能可以对网页翻译生效

**Comment by chunibyocola** [comment]
这不是一个很好的做法，文本在网页中其实是分成很多段的，并不是像划字翻译那样能直接获取所划取的文本，所以预期想要达成的效果很多时候是达不到的。同时这会造成非常大的运算量，根据用户设置的不同可能会造成严重的网页卡顿问题。
