### ISSUE TITLE
请问是否可以在网页的翻译面板中添加翻译的英语

### ISSUE THREAD

**Issue by freedomspiritJohn** [chunibyocola/sc-translator-crx#157]
希望添加一个这样的选项，让用户选择是否把要翻译的单词或句子也展示在网页翻译面板中
![image](https://github.com/chunibyocola/sc-translator-crx/assets/129288685/1d1b0342-e1ea-4628-b301-398853486b9b)
比如我这里fanyi翻译的是sudden，但是整个面板中只在例句中才出现了这个单词，希望在开头也可以添加，这样便于观察。

**Comment by chunibyocola** [comment]
输入框里就是原文，可以通过自定义 CSS 来让其默认开启。
