### ISSUE TITLE
希望增强一下弹出的位置

### ISSUE THREAD

**Issue by freedomspiritJohn** [chunibyocola/sc-translator-crx#158]
不管距离上下界面多远，他总是会向下弹出，导致内容被覆盖因此，弹出网页翻译窗口前，是否可以先判断距离低端的距离，然后选择在上面弹出还是在选定的单词的下面弹出窗口，如图所示。
![建议](https://github.com/chunibyocola/sc-translator-crx/assets/129288685/a2e1d83d-8eff-4524-9e1b-e03ac9d25e43)
此外是否可以添加独立弹窗窗口是否跟随页面滚动的选项

**Comment by chunibyocola** [comment]
根据你的 GIF 也可以看出，弹出窗口前是会判断底端距离并保持整个窗口都在网页中的，但是翻译请求完毕后新增的内容会导致面板高度增加。我明白你可能是想要在翻译请求完成后也调整面板，但是这其实是一种不好的用户体验——面板会没有规律地移动。再就是因为复数翻译源的存在，如果翻译请求后调整面板，那么面板会被调整多次。

在这种情况下，我建议你启用“记住面板固定的位置”，这样的话无论在哪里点击翻译，只要处于固定的状态所处的位置都不会变。同时你还可以启用“打开面板时将其固定”，这样可以连点击固定按钮的操作都省略掉。

> 此外是否可以添加独立弹窗窗口是否跟随页面滚动的选项

独立翻译窗口的功能是十分受限制的，只能使用浏览器所提供的接口。
