### ISSUE TITLE
Modifier keys for "Display the original text when the mouse hovers over the translation"

### ISSUE THREAD

**Issue by Dook1** [chunibyocola/sc-translator-crx#159]
Would you please add the option to select modifier keys(Ctrl, Shift, Alt) for "Display the original text when the mouse hovers over the translation"?

**Comment by chunibyocola** [comment]
> select modifier keys(Ctrl, Shift, Alt) for "Display the original text when the mouse hovers over the translation"

I can't associate modifier keys with "Display the original text when the mouse hovers over the translation". Can you explain the process, thanks.

**Comment by Dook1** [comment]
If mouse hover over node check if modifier key is pressed, if it is pressed then show tooltip with original text.

**Comment by chunibyocola** [comment]
Thanks, I think it will help if user don't want to see the original-text panel so often but they do need to see the panel sometime.

**Comment by Dook1** [comment]
Yes, you are right, Ctrl is the only option.

**Comment by chunibyocola** [comment]
New option named "Display original text only when 'Ctrl' key is pressed at the same time" has been added, you can find it below “Display the original text when the mouse hovers over the translation” option in the next version.
