### ISSUE TITLE
小建议：“原文 + 译文”模式的“译文样式自定义”，可选择作用于纯“译文”模式下。

### ISSUE THREAD

**Issue by hs01a** [chunibyocola/sc-translator-crx#160]
你好：
如题（小建议：“原文 + 译文”模式的“译文样式自定义”，可选择作用于纯“译文”模式下。）
作用：能一眼区分没与有翻译的文字。

**Comment by chunibyocola** [comment]
一般来说，看到的文字都会被翻译，只是可能翻译请求速度慢会导致看到没被翻译的文字又或者文字处于不应被翻译的区域里。

样式自定义因为涉及到字体颜色，页面中会存在不同颜色的背景（比如夜间模式为主的页面），会造成难以分辨的弊端。然后就是比如使用了下划线，想象了一下页面里所有文字都有下划线，感觉有点难受。

所以目前来说不太可能会去实现这个功能，但同样非常感谢你所提出的建议！

**Comment by hs01a** [comment]
嗯。谢谢你的回应。
按我的建议，虽然但是，既然都“译文样式自定义”了，就没有“受不同颜色的背景影响”或“影响美观”一说吧！？
我只是建议：在“译文样式自定义”中，加多一个选项：“也作用于纯‘译文’”。默认为不选就是了。
其作用：如：YT首页有多种语言的的标题，纯‘译文’模式下，按我建议，那么就一眼就能区别哪些原标题是简体中文，哪些原标题是非简体中文了。（多种语言评论，同理）
如果用“原文 + 译文”模式，翻译出标题的译文很多隐藏了｛由于加长的文字（译文），但又没加多空间｝。

仅个人认为哈。
