### ISSUE TITLE
【增强】独立翻译面板功能增强

### ISSUE THREAD

**Issue by freedomspiritJohn** [chunibyocola/sc-translator-crx#163]
希望在打开或者调出独立翻译面板的时候，可以选择每次打开独立控制面板的时候是否同时打开置顶功能；还有希望独立面板的时候可以设定是否自动读取剪切板的内容。

**Comment by chunibyocola** [comment]
> 希望在打开或者调出独立翻译面板的时候，可以选择每次打开独立控制面板的时候是否同时打开置顶功能

这是做不到的，扩展只能使用浏览器提供的权限。

> 还有希望独立面板的时候可以设定是否自动读取剪切板的内容。

这是已有的功能，只需要启用“自动粘贴到输入框中”即可。

**Comment by freedomspiritJohn** [comment]
> > 希望在打开或者调出独立翻译面板的时候，可以选择每次打开独立控制面板的时候是否同时打开置顶功能
> 
> 这是做不到的，扩展只能使用浏览器提供的权限。
> 
> > 还有希望独立面板的时候可以设定是否自动读取剪切板的内容。
> 
> 这是已有的功能，只需要启用“自动粘贴到输入框中”即可。

但是我已经开启这个功能了，失效了吗？
![PixPin_2024-02-17_23-32-05](https://github.com/chunibyocola/sc-translator-crx/assets/129288685/30c816cc-50b3-4f44-8c94-25cba9ea5c20)

**Comment by chunibyocola** [comment]
抱歉，我之前没完全理解你的意思，原来是监听剪切板的功能，这同样是没有被浏览器提供的。

严格来说，这是可以实现的，但这会需要频繁去读取剪切板的内容，对用户来讲会比较不舒服，我先考虑一下吧。
