### ISSUE TITLE
增强建议：单词显示等级

### ISSUE THREAD

**Issue by freedomspiritJohn** [chunibyocola/sc-translator-crx#164]
是否可以做到输入单词后，显示英语单词是什么要求的比如四级六级，考研，托福，雅思。我的实现想法是从网络或者本地查询输入的单词获取单词等级

**Comment by chunibyocola** [comment]
目前使用的源均没有这种功能，且这个功能一般是词典类的应用所具备的。目前用户可以通过自定义翻译源来做到这一点。

**Comment by aozhangchina** [comment]
感觉没有必要，四六级不是刚需，，也不算主要的用户群，学习四六级可以找专业的软件或书籍Best regards,Dr. Ao ZhangCollege of Bioscience and BiotechnologyShenyang Agricultural University (SYAU)Dongling Road 120, Shenhe District, Shenyang City, Liaoning Province, China在 2024年2月21日，20:13，freedomspiritJohn ***@***.***> 写道：﻿
是否可以做到输入单词后，显示英语单词是什么要求的比如四级六级，考研，托福，雅思。我的实现想法是从网络或者本地查询输入的单词获取单词等级
