### ISSUE TITLE
独立翻译窗口如何选择翻译源

### ISSUE THREAD

**Issue by freedomspiritJohn** [chunibyocola/sc-translator-crx#165]
![image](https://github.com/chunibyocola/sc-translator-crx/assets/129288685/7b6a20a5-4ca4-4802-a7ff-b142af5e0ed2)
目前我的独立翻译窗口使用了谷歌和微软的翻译。但是由于谷歌没有微软翻译的准确，所以我想去掉谷歌，只留下微软，但是每次打开独立翻译窗口谷歌翻译都会恢复。怎么才能永久去掉某个翻译源

**Comment by chunibyocola** [comment]
在选项页中的“独立翻译窗口”栏中也有提到

> 独立翻译窗口使用“复数翻译模式”的翻译面板，与其共用同一套翻译设置。

你需要在“默认翻译选项”中启用“复数翻译模式”后取消选择谷歌翻译。
