### ISSUE TITLE
百度划词翻译无法使用

### ISSUE THREAD

**Issue by Amanoki** [chunibyocola/sc-translator-crx#166]
可能有两三星期时间划词翻译的百度选项无法使用了，显示“错误：服务器返回了一个意外的结果。重试”。希望能够修复，谢谢！

**Comment by chunibyocola** [comment]
我目前使用上是没有问题的。我之前挖掘过，似乎是百度翻译那边的 cookie 问题，比如 IP 变换后会触发这个问题。只能由用户那边去清除百度翻译的缓存后访问官网试试能不能修复这个问题。

如果还是不行的话可以继续在此 issue 下留言。

**Comment by aozhangchina** [comment]
﻿我这边是bing翻译出现意外问题Best regards,Dr. Ao ZhangCollege of Bioscience and BiotechnologyShenyang Agricultural University (SYAU)Dongling Road 120, Shenhe District, Shenyang City, Liaoning Province, China在 2024年3月6日，09:45，sweetcola ***@***.***> 写道：﻿
我目前使用上是没有问题的。我之前挖掘过，似乎是百度翻译那边的 cookie 问题，比如 IP 变换后会触发这个问题。只能由用户那边去清除百度翻译的缓存后访问官网试试能不能修复这个问题。
如果还是不行的话可以继续在此 issue 下留言。

**Comment by chunibyocola** [comment]
Bing 我倒是不知道是怎样触发的，但是操作就更简单，需要在官网那边翻译一下触发验证码就可以了。官方那边的限制这边是无能为力的。

**Comment by aozhangchina** [comment]
怎么才能触发验证码？Best regards,Dr. Ao ZhangCollege of Bioscience and BiotechnologyShenyang Agricultural University (SYAU)Dongling Road 120, Shenhe District, Shenyang City, Liaoning Province, China在 2024年3月6日，12:03，sweetcola ***@***.***> 写道：﻿
Bing 我倒是不知道是怎样触发的，但是操作就更简单，需要在官网那边翻译一下触发验证码就可以了。官方那边的限制这边是无能为力的。

**Comment by chunibyocola** [comment]
你的情况可能不是我说的那个，你的应该是网络相关的问题，需要在选项页中找到“默认翻译选项”并关闭/打开"在 URL 中使用'.cn'"选项。

**Comment by Amanoki** [comment]
> 我目前使用上是没有问题的。我之前挖掘过，似乎是百度翻译那边的 cookie 问题，比如 IP 变换后会触发这个问题。只能由用户那边去清除百度翻译的缓存后访问官网试试能不能修复这个问题。
> 
> 如果还是不行的话可以继续在此 issue 下留言。

谢谢回复，请问下怎样删除缓存呢？我用Chrome，去设置-隐私和安全-第三方cookie-所有网站数据和权限，然后找到 fanyi.badu 的条目删除。然后重启浏览器等试了下仍然出错，无痕模式也是出错。还有什么其他东西需要清吗？

**Comment by chunibyocola** [comment]
那可能需要把 baidu.com 的 cookie 也同时删除掉，还不行的话可以试试换另一个浏览器看看有没有问题。网络相关问题确实是比较难办的，甚至还有可能是 IP 的问题。

**Comment by Amanoki** [comment]
谢谢！确实，把 baidu 整个删除之后就可以了。
另外请问一下，用 bing 的时候如果划词超出大概150+词语，也会显示 服务器返回了一个意外的结果。这个是官方那边的限制吗？有一些方法可以解除它吗？
