### ISSUE TITLE
扩展安装后图标是黑白的，怎么更改成彩色的

### ISSUE THREAD

**Issue by qwer52145** [chunibyocola/sc-translator-crx#167]

**Comment by chunibyocola** [comment]
黑白说明当前网页不可用，刷新页面即可（扩展商店除外）

**Comment by qwer52145** [comment]
我试了一下，好像所有网页都是显示黑白的扩展图标，刷新也不管用，是需要单独设置什么吗

**Comment by chunibyocola** [comment]
请问你用的是什么浏览器，然后扩展的名称是什么，版本是什么。

**Comment by qwer52145** [comment]
edge浏览器，扩展名称是可可翻译，浏览器版本102，扩展版本5.3.0

**Comment by chunibyocola** [comment]
我在 Edge 上卸载后重装也没有问题，所以只能尝试一下禁用后再次启用、重启浏览器之类的操作了，因为我在哪个浏览器都无法复现这个问题。

**Comment by qwer52145** [comment]
您好，我找了个高版本的浏览器试了一下，是可以的，可能我现有的浏览器版本太低了

**Comment by qwer52145** [comment]
如果方便的话，下次版本更新可以优化一下适配低版本edge，因为高版本的edge浏览器确实不怎么友好，谢谢

**Comment by chunibyocola** [comment]
你好，相关内容自 88 版本以来没有做过任何改动，扩展的标准也没有变，如果是因为版本的原因，那只能是那个版本的问题了。
