### ISSUE TITLE
百度翻译失效

### ISSUE THREAD

**Issue by qianoix** [chunibyocola/sc-translator-crx#168]
百度翻译的接口好像失效了，最近使用一直显示：错误：服务器返回了一个意外的结果。重试
![Snipaste_2024-03-16_16-04-48](https://github.com/chunibyocola/sc-translator-crx/assets/70510758/270bb237-1f2f-46aa-a7e4-7e38f5eca035)

**Comment by chunibyocola** [comment]
这个问题似乎是 cookie 相关的问题，比如 IP 切换的话回发生这个问题。目前只能由用户那边手动去删除 `fanyi.baidu.com` 和 `baidu.com`的缓存了。如果删除后仍然不能使用，可以继续在这个 issue 下留言，谢谢。
