### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by x089866221631** [chunibyocola/sc-translator-crx#169]
bing翻译和百度翻译使用显示错误：服务器返回了一个意外结果。

**Comment by chunibyocola** [comment]
目前这两个我在使用上都是正常的，Bing 的话可以尝试在选项页中切换`在 URL 中使用“.cn”（例如：translate.google.cn）`选项。百度的话可以尝试删除`baidu.com`和`fanyi.baidu.com`的缓存。

目前百度反映问题的人较多，且我注意到 API 有部分改变，我会尝试去更新一下的。
