### ISSUE TITLE
When using the "Translate current page" function on Notion, the entire page cannot be translated at once

### ISSUE THREAD

**Issue by TW527E** [chunibyocola/sc-translator-crx#170]
When you use the "Translate current page" function on Notion, it looks like nothing has been translated, but when you click on any of the items, the item will be translated into the target language, but other No change, until you click on other items, other items will be translated together.

**Comment by chunibyocola** [comment]
Page translation can't work on some websites which oppose to be translated. I don't use Notion, so I am unable to test it. I tried Notion's offical website, it works.

You can try to translate the page this extension can't work on through the page translation provided by browser, if do translate it well, I will try to figure out why it happens. Thanks.

**Comment by TW527E** [comment]
I used ARC for Windows ["Getting Started with Arc for Windows!"](https://browserinc.notion.site/Getting-Started-with-Arc-for-Windows-145ece36acbb40f381ce1817747cb7ca) to demonstrate the problem. (Because I just switched to ARC for Windows) (He recently allowed people with accounts on the Mac version to log in to the Windows version directly.)

![Screenshot_2024-03-30_16-31-24](https://github.com/chunibyocola/sc-translator-crx/assets/37478187/fe964f29-fd67-4569-a6f0-1aba1f444e91)

**Comment by chunibyocola** [comment]
Thanks for providing more information, it is interesting to see sentence get translated by clicking. This page is definitely not recommended to be translated, I tried offical Google page translation, the page become so slow and can't show any translation. So this issue is not able to be fixed by extension side
