### ISSUE TITLE
打开独立翻译面板，里面有内容自动朗读

### ISSUE THREAD

**Issue by YinBenQian** [chunibyocola/sc-translator-crx#172]
首先感谢作者的无私分享，作者大大能不能做一个当我打开独立翻译面板的时候（我使用了监听剪切板的功能）这就意味着当我复制一段文字，并且打开独立翻译面板会自动翻译，我想要要翻译的时候自动朗读单词或文本，平常开发总是接触大量的英文，对于我这种英文苦手来说，非常痛苦，需要频繁点击朗读标志（想要学习一下单词的发音，提升一下单词量）对我来说十分痛苦.作者大大能不能开发这样的一个功能，我可以为作者大大献上50元的小心意（也不知道是不是太少了）

**Comment by chunibyocola** [comment]
抱歉现在才回复你，之前电脑主板炸了，这个项目就一直搁置了，这个功能预计是一些用户所需要的，但是一些细节需要去斟酌

比如当用户使用复数翻译源时应该让哪个源来阅读等等，目前我想的是使用浏览器自带的朗读功能来朗读，但是暂停键又不知道放哪里最合适。

如果有自己的想法或者更好的建议可以分享一下，谢谢。
