### ISSUE TITLE
希望添加用翻译当前页面的快捷键切换翻译状态

### ISSUE THREAD

**Issue by mofazhe** [chunibyocola/sc-translator-crx#174]
![image](https://github.com/chunibyocola/sc-translator-crx/assets/41715438/a541d995-cc7c-4d63-b774-ab0806f93672)
比如我设置的这个alt+r，按一次会翻译全文，再按一次应该关闭翻译全文，就是回到翻译全文前的状态。

能开启翻译全文的功能是有的，就是希望添加这个再按一次该快捷键关闭翻译全文的功能。

**Comment by chunibyocola** [comment]
你图中标记的“翻译当前页面”的上面的“切换当前网页的网页翻译状态”应该就是你所想要的功能，你可以尝试一下。
