### ISSUE TITLE
Bing translate error

### ISSUE THREAD

**Issue by dzungitx** [chunibyocola/sc-translator-crx#176]
Error: Connection time out.
Windows. MS Edge and Vivaldi browser. Version 5.6.0
![ZYZEN_11 09 2024_17 26 23 186](https://github.com/user-attachments/assets/f67244f6-f251-4dbe-abd7-3fc02db52455)

**Comment by chunibyocola** [comment]
![image](https://github.com/user-attachments/assets/849660a1-f7bb-423f-9dec-bd4d5694b8b5)
It works well, try enable/disable "Use '.cn' in URL" option, and make sure you can access [Bing Translator](https://bing.com/translator).

**Comment by chunibyocola** [comment]
This issue will be closed because there is no response.
