### ISSUE TITLE
"Translate dynamically generated content" doesn't work on reddit.com

### ISSUE THREAD

**Issue by Dook1** [chunibyocola/sc-translator-crx#178]
The text that appears after clicking on "... more replies" is not translated.
For example here: https://www.reddit.com/r/androidroot/comments/1b5onw5/ksu_vs_magisk/

**Comment by chunibyocola** [comment]
This issue happens when there is content inside dynamically generated element with shadow root attached, I have fixed it.

Thanks for your report!
