### ISSUE TITLE
未对 translate="no" 正确处理

### ISSUE THREAD

**Issue by SteveZMTstudios** [chunibyocola/sc-translator-crx#182]
部分元素可能为使用字体的装饰，或者不应当被翻译的语义插件。
根据[MDN文档](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/translate)，它们会被标记上translate="no" 标签。

已经测试Google翻译和Edge浏览器自带翻译功能会对相应的标记进行忽略处理。
但是可可翻译仍然会对那些项目元素进行翻译，导致使用font作为标记的图标错乱。
如下为可可翻译的效果截图（使用箭头标示了被错误翻译的部分）（以[我的博客](https://blog.stevezmt.top/)为例）
![image](https://github.com/user-attachments/assets/e085f927-dc7d-48d9-940d-11fe6c2fbb86)

如下为Google Chrome浏览器内置翻译的效果
![image](https://github.com/user-attachments/assets/af814ce5-1778-4485-b8ee-7f6d46376f37)

如下为页面部分源代码
![image](https://github.com/user-attachments/assets/dca0d0b0-2a98-4e4c-98f0-c27a0a99c181)

如果需要我提供更多技术细节请继续回复。

**Comment by chunibyocola** [comment]
感谢，我没有注意到这一点，只对 className 中的 notranslate 做了处理。

会在下个版本中改进这一点的
