### ISSUE TITLE
The page cannot be centered

### ISSUE THREAD

**Issue by cantona97** [chunibyocola/sc-translator-crx#2]
The page（like www.ipaddress.com) cannot be centered.  
【v2.7.1   Windows 10 & MacOs Big Sur Microsoft Edge】

**Comment by chunibyocola** [comment]
This issue due to the style of `body>div { max-width: 1200px; overflow: hidden; width: 100%; }`.
I fixed it in `v3.0.0`, which will publish in tomorrow. 
Thanks for your feedback!

**Comment by cantona97** [comment]
Thank you!
