### ISSUE TITLE
在网页中插入翻译结果后能不能在原文和翻译下面加一个下划线或者标注。

### ISSUE THREAD

**Issue by kmxj2020** [chunibyocola/sc-translator-crx#21]
在网页中插入翻译结果后能不能在原文和翻译下面加一个下划线或者标注。

**Comment by chunibyocola** [comment]
我也确实有这样的想法，在使用的过程中经常比较难去分清。但一直不知道该怎么处理才能更好的凸显出来又不影响插入结果之前的体验。

我会在译文下方加下划线看看效果。原文方面的话大概会先保留。

**Comment by kmxj2020** [comment]
一点个人想法：
1. 修改插入文字的颜色，字体大小，粗细，斜体等中的一个或者多个格式；
2. 在原文的上方插入译文；
3. 只把原文标下标或者波浪线，当鼠标放在原文上有气泡显示译文（若一句话里面有包含关系的词句，可以用不同颜色的下划线）；


另：能加上生词本功能吗？

**Comment by chunibyocola** [comment]
主要还是需要考虑的东西太多了。比如：用户可能会跨元素选择（且不完全跨越）、网页的背景颜色和文字颜色等因素。还有 Chromium 自身的一个`getSelection().toString()`的 Bug 导致用户选择到插入的元素也会被包含在里面。因此我不会倾向于选择太激进的方式。

> 1. 修改插入文字的颜色，字体大小，粗细，斜体等中的一个或者多个格式；
> 2. 在原文的上方插入译文；
> 3. 只把原文标下标或者波浪线，当鼠标放在原文上有气泡显示译文（若一句话里面有包含关系的词句，可以用不同颜色的下划线）；

目前来讲第 2 点不太可行（考虑到跨元素选择），不过你所提出的第 1 点和第 3 点是非常值得去尝试的。

> 另：能加上生词本功能吗？

也不是没有这个想法。现在已经有当前网页内的翻译历史记录，在一定范围内是可以替代这个功能的。

目前还是朝着”网页内“的这个概念在走，不过未来的事也说不定。

感谢你的反馈！
