### ISSUE TITLE
Failed connection to translation service providers.

### ISSUE THREAD

**Issue by minshifu** [chunibyocola/sc-translator-crx#23]
Thank you for your addon. It is very useful and promising. But one bug is persistent. That is , failed connection with translation service providers. Sometimes it is Google Translater as shown by the image below. Sometimes it is Bing Translator. Sometimes both.  Besides, Translation History is always empty and does not seem to be working. Could you pls fix it?  
Thank you and best regards!

![图片](https://user-images.githubusercontent.com/5119952/131846796-09b8f36e-888e-48be-af4d-938963d3c81b.png)

![图片](https://user-images.githubusercontent.com/5119952/131847403-f9178e63-0b3b-4dc4-b0e4-bec5eb084ed9.png)

**Comment by chunibyocola** [comment]
Hello, thanks for using my addon.

If you send too much requests in a period of time, both Google and Bing will block the connection for a while. For Google, it is half an hour.
It is a big compromise of unofficial.
I have optimized the request times to reduce the chance of the connection blocking.
Maybe the only way to fix it is to use the official API which will require you to apply for authenticating. But now this is not a priority.

**Comment by chunibyocola** [comment]
> Translation History is always empty and does not seem to be working.

Could you please provide the website to me to check about it. In my testing, it is OK. Or it is no records in all websites?

**Comment by minshifu** [comment]
> 
> 
> > Translation History is always empty and does not seem to be working.
> 
> Could you please provide the web_site_ to me to check about it. In my testing, it is OK. Or it is no records in all web_site_s?

Yes,for me it does not work on any webpage.

**Comment by chunibyocola** [comment]
Did you use this feature like this?
![translate-history](https://user-images.githubusercontent.com/46666257/132092881-31bee1c4-b548-4103-bab7-38a572d83a85.gif)


The translate request in the popup page will not be recorded.

**Comment by minshifu** [comment]
> 
> 
> Did you use this feature like this?
> ![translate-history](https://user-images.githubusercontent.com/46666257/132092881-31bee1c4-b548-4103-bab7-38a572d83a85.gif)
> 
> The translate request in the popup page will not be recorded.

Thank you. It is fixed. But it seems the history will be lost after page reloading.

**Comment by chunibyocola** [comment]
> But it seems the history will be lost after page reloading.

Yes, it is how it work.

**Comment by chunibyocola** [comment]
The mechanism of requesting Google translate has been updated. The probability of "BAD_REQUEST (http 429)" should be reduced.

This improvment will be released in version 3.11.0 which will be published next Monday. There are still a series of tests to be completed.

If you meet 429 again in v3.11.0, you can reopen this issue.

Thanks for your feedback!

**Comment by minshifu** [comment]
> 
> 
> The mechanism of requesting Google translate has been updated. The probability of "BAD_REQUEST (http 429)" should be reduced.
> 
> This improvment will be released in version 3.11.0 which will be published next Monday. There are still a series of tests to be completed.
> 
> If you meet 429 again in v3.11.0, you can reopen this issue.
> 
> Thanks for your feedback!

Thank you so much! I will.
