### ISSUE TITLE
希望增加自动翻译选项等

### ISSUE THREAD

**Issue by YuI2333** [chunibyocola/sc-translator-crx#27]
1. 希望增加一个这样的名单，名单内的域名自动网页翻译。
![48_15](https://user-images.githubusercontent.com/26202875/137619485-ce5edaf2-e44d-4cb3-acad-384405c6c7c5.png)

2. 快捷键希望支持切换原文，例如我现在Alt+Q是网页翻译，再次按Alt+Q可以显示原文。

3. 关于右键菜单，翻译网页后右键菜单依然显示“翻译当前页面”，希望此时显示为“显示原文”。

4. 右下角的控制栏真的很有存在的必要吗？反正我感觉挺多余的，希望增加开关彻底去掉。🤣

最后感谢大佬！辛苦啦！！

**Comment by chunibyocola** [comment]
> 1. 希望增加一个这样的名单，名单内的域名自动网页翻译。

这个要实现还是比较简单的，但是目前的网页翻译算法还没有实装监听元素变化的功能，不能像原生谷歌网页翻译那样有新内容就翻译新内容。

所以就会导致有可能只翻译了一小部分内容（其它的并没有在翻译前加载），之后需要用户关闭翻译再启动翻译。所以这个功能需要等我实装了监听元素变化的算法之后才会去增加。

这个算法我已经是想好怎么写了，但我不确定我是否应该这样做，因为实装之后是有可能会产生频繁请求接口的现象（这也是谷歌和微软目前的做法，虽然发生的概率会很低但就是会发生）。

> 2. 快捷键希望支持切换原文，例如我现在Alt+Q是网页翻译，再次按Alt+Q可以显示原文。
> 3. 关于右键菜单，翻译网页后右键菜单依然显示“翻译当前页面”，希望此时显示为“显示原文”。

也许我可以增加一个“切换网页翻译展示方式”的快捷键。

> 4. 右下角的控制栏真的很有存在的必要吗？反正我感觉挺多余的，希望增加开关彻底去掉。

控制栏可以切换翻译结果的显示方式、切换翻译源、切换目标语言和关闭网页翻译，可以做到比较多的操作，所以还是有必要的。目前已经有选项来让控制栏不显示了，但需要你先启用“激活网页翻译后直接翻译”选项，再启用“首次激活时不显示控制栏”选项。

**Comment by vmarsed** [comment]
自动翻译 +1 

原来控制栏还能切换翻译展示方式..太好了
可可支持 3 种翻译展示方式非常喜欢.. 经常要到选项里换...没想到控制栏可以换~~

**Comment by wellchichi** [comment]
选中多个段落翻译的时候，如果能保持原段落的格式就更好了。  不然全部格式化成一堆文字，看着很难受。。

**Comment by wellchichi** [comment]
> 选中多个段落翻译的时候，如果能保持原段落的格式就更好了。 不然全部格式化成一堆文字，看着很难受。。

这个插件真的舒服啊，功能强

**Comment by chunibyocola** [comment]
“翻译动态生成的内容”功能在 v4.5.0 中已经支持，预计在下一个版本中实装“网页自动翻译”的功能。

“网页自动翻译”功能将会以域名白名单的形式执行，不会是自动判断网页语言与目标语言不同就自动翻译的这种模式，并且必须要启用“翻译动态生成的内容”选项后才能使用。在目前的构思中，检测到用户启用“网页自动翻译”后会在控制栏中加入一个复选框，用来启用/取消对当前网站的自动翻译。

需要注意的是，“在部分网站中使用可能会导致无限翻译请求”的问题还是无法解决，所以我个人是建议不开启的（绝大部分网站是没问题的）。

> 选中多个段落翻译的时候，如果能保持原段落的格式就更好了。 不然全部格式化成一堆文字，看着很难受。。

应该会出一个新的选项“句子自动分段”，这个功能根据翻译源的不同，表现也会不同。

> 如果能有个Talent里面的截图翻译就更好了，再次感谢！

目前没有这个想法，我认为截图翻译不应该由网页来发起，而且桌面端已经有十分成熟的应用了。

**Comment by wellchichi** [comment]
> > 如果能有个Talent里面的截图翻译就更好了，再次感谢！
> 
> 目前没有这个想法，我认为截图翻译不应该由网页来发起，而且桌面端已经有十分成熟的应用了。

嗯，确实是有，只不过需要多开个软件，截图翻译也算是翻译里比较常用的一个功能。 不过无所谓，依然是我认为最好的翻译插件…

**Comment by theowenyoung** [comment]
这个插件目前支持自动翻译，如果有帮助的话，可以参考： https://github.com/FilipePS/Traduzir-paginas-web

感谢作者的工作。

**Comment by xxnuo** [comment]
> “翻译动态生成的内容”功能在 v4.5.0 中已经支持，预计在下一个版本中实装“网页自动翻译”的功能。
> 
> “网页自动翻译”功能将会以域名白名单的形式执行，不会是自动判断网页语言与目标语言不同就自动翻译的这种模式，并且必须要启用“翻译动态生成的内容”选项后才能使用。在目前的构思中，检测到用户启用“网页自动翻译”后会在控制栏中加入一个复选框，用来启用/取消对当前网站的自动翻译。
> 
> 需要注意的是，“在部分网站中使用可能会导致无限翻译请求”的问题还是无法解决，所以我个人是建议不开启的（绝大部分网站是没问题的）。
> 
> > 选中多个段落翻译的时候，如果能保持原段落的格式就更好了。 不然全部格式化成一堆文字，看着很难受。。
> 
> 应该会出一个新的选项“句子自动分段”，这个功能根据翻译源的不同，表现也会不同。
> 
> > 如果能有个Talent里面的截图翻译就更好了，再次感谢！
> 
> 目前没有这个想法，我认为截图翻译不应该由网页来发起，而且桌面端已经有十分成熟的应用了。

请问白名单网页自动翻译的功能可以实装发布了吗？

**Comment by chunibyocola** [comment]
目前正在测试中，预计会在下周一发布。
