### ISSUE TITLE
使用谷歌翻译时很不稳定，经常会跳出“重试”，无法解决这个问题

### ISSUE THREAD

**Issue by mdpuemian** [chunibyocola/sc-translator-crx#3]
请问目前可以有解决的方法吗？很喜欢这个插件，但是重装等方法都试过了，一天可用一天不可用有点麻烦

**Comment by chunibyocola** [comment]
这个问题大概和你的网络环境有关，在我的网络环境下没有发生过这种问题。
翻译请求的是`translate.googleapis.com`这个网址，你可以尝试使用某些方法来让你能更顺场地访问这个网址。
如果百度翻译没有产生这种问题的话，你可以试试默认使用百度翻译。

**Comment by mdpuemian** [comment]
好的，感谢
