### ISSUE TITLE
sync settings

### ISSUE THREAD

**Issue by epfromer** [chunibyocola/sc-translator-crx#33]
This extension is super useful, thank you!  

Is it possible to synchronize settings, or perhaps have import/export settings function?  I'd like to have the same settings between my desktop and laptop.  I'm using Edge.

**Comment by chunibyocola** [comment]
Thanks!

- Is it possible to synchronize settings, or perhaps have import/export settings function?
It is possible but I am not familiar with this. Several implementations below:
1. Through Extension API `chrome.storage.sync`, that require you to log in to your account in each browsers.
2. Generate a string which contains all the data in storage. Then you need to copy this to another browser.
3. A ScTranslator account system.

Each of these implementations has its own advantages and disadvantages. At present, I prefer the first implementation, but it needs time to debug. If possible, I will add a button named `Synchronize your settings to others browsers`.
