### ISSUE TITLE
bing和百度不能用了

### ISSUE THREAD

**Issue by Misakei** [chunibyocola/sc-translator-crx#36]
![image](https://user-images.githubusercontent.com/33886929/152627786-6975888f-1d91-4b38-807e-504f36386e04.png)

**Comment by chunibyocola** [comment]
你好，经过我测试，都是正常的。
![screenshot](https://user-images.githubusercontent.com/46666257/152643299-c8e87da9-d7da-4895-8bda-2d76ff64fae1.png)

Bing 翻译你可以打开/关闭“在 URL 中使用‘.cn’”选项后再尝试。
Baidu 翻译你可以访问一次 [百度翻译官网](https://fanyi.baidu.com) 后再尝试。
