### ISSUE TITLE
关于网页翻译不全的问题

### ISSUE THREAD

**Issue by YuI2333** [chunibyocola/sc-translator-crx#37]
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel
![38_55](https://user-images.githubusercontent.com/26202875/156738826-67073e1f-6313-41af-8267-6287ab1391ea.png)
有空了麻烦看一下，感谢！！

另外，请问这个扩展是你上架的还是有人参考了你的代码？0.0
https://microsoftedge.microsoft.com/addons/detail/%E7%BF%BB%E8%AF%91/ffbkgbihhpbafkdkhopjfpagpngjnodh

**Comment by chunibyocola** [comment]
你好，我看了一下，这个问题好像只出现在 Google 网页翻译上，你暂时可以用 Microsoft 网页翻译代替（虽然这样还不如直接用自带的）。现在看来是 API 更新了，导致翻译结果的解析出了问题，应该很快可以修复。

> 另外，请问这个扩展是你上架的还是有人参考了你的代码？0.0
并不是我上架的。

**Comment by chunibyocola** [comment]
![web-translation](https://user-images.githubusercontent.com/46666257/156744322-54de7e2c-3fb2-40c6-8cab-ebe6435542d6.png)
修复好了，等等会上架 v3.17.1，算上审核可能还要等几天。

**Comment by chunibyocola** [comment]
审核已通过，更新一下扩展就可以了。

感谢反馈！
