### ISSUE TITLE
设置备份选项

### ISSUE THREAD

**Issue by a76yyyy** [chunibyocola/sc-translator-crx#38]
请问能否提供将设置备份或导入至文件或者onedrive的选项？
可以参考油猴插件设置备份的功能

**Comment by chunibyocola** [comment]
> 请问能否提供将设置备份或导入至文件或者onedrive的选项？

可以的，但在有“同步设置至其他浏览器”的情况下，我想知道在哪种状况下会使用以文件的方式来同步。

**Comment by a76yyyy** [comment]
> > 请问能否提供将设置备份或导入至文件或者onedrive的选项？
> 
> 可以的，但在有“同步设置至其他浏览器”的情况下，我想知道在哪种状况下会使用以文件的方式来同步。

或许是一种可选的方式，比如重装系统或者国内谷歌浏览器无法同步等
