### ISSUE TITLE
这个网页翻译，经常没反应是怎么原因呢，比如YouTube  翻译无效，没反应。

### ISSUE THREAD

**Issue by yangchen158158** [chunibyocola/sc-translator-crx#41]
这个网页翻译，经常没反应是怎么原因呢，比如YouTube  翻译无效，没反应。

**Comment by chunibyocola** [comment]
我这边试到是有效的，请你提供一下浏览器版本以及扩展的版本，以及使用的网页翻译源是什么。

如果你是说点击翻译之后只翻译了一部分，往下滚动后评论部分没有被翻译的话，是正常的，需要关闭之后再次开启。

**Comment by yangchen158158** [comment]
鲸鱼浏览器，https://chrome.google.com/webstore/detail/sctranslator/icfnljfpacimpcbpammmbclmhenimhfc

**Comment by yangchen158158** [comment]
感觉 如果当前页面很多不同国家语言，这个会失效， 在别的页面，比如就现在https://github.com/ 都是可以快捷键一按，就翻译出来的

**Comment by yangchen158158** [comment]
翻译是不是有间隔时间吗 。打开不同页面，不能立刻翻译吗！

**Comment by yangchen158158** [comment]
就油管翻译有问题， 别的页面都正常。 设置的翻译快捷键ALT+F。 快捷键一按就翻译出来了。

**Comment by yangchen158158** [comment]
yangchen158158 <https://github.com/yangchen158158> commented 13 minutes ago
<https://github.com/chunibyocola/sc-translator-crx/issues/41#issuecomment-1088904553>

鲸鱼浏览器，
https://chrome.google.com/webstore/detail/sctranslator/icfnljfpacimpcbpammmbclmhenimhfc
[image: @yangchen158158] <https://github.com/yangchen158158>

Author
yangchen158158 <https://github.com/yangchen158158> commented 13 minutes ago
<https://github.com/chunibyocola/sc-translator-crx/issues/41#issuecomment-1088904815>

版本
3.17.1
[image: @yangchen158158] <https://github.com/yangchen158158>

Author
yangchen158158 <https://github.com/yangchen158158> commented 5 minutes ago
<https://github.com/chunibyocola/sc-translator-crx/issues/41#issuecomment-1088918797>

https://www.youtube.com/watch?v=9JJygKtMsXw
[image: @yangchen158158] <https://github.com/yangchen158158>

Author
yangchen158158 <https://github.com/yangchen158158> commented 4 minutes ago
<https://github.com/chunibyocola/sc-translator-crx/issues/41#issuecomment-1088920702>

感觉 如果当前页面很多不同国家语言，这个会失效， 在别的页面，比如就现在https://github.com/ 都是可以快捷键一按，就翻译出来的
[image: @yangchen158158] <https://github.com/yangchen158158>

Author
yangchen158158 <https://github.com/yangchen158158> commented 3 minutes ago
<https://github.com/chunibyocola/sc-translator-crx/issues/41#issuecomment-1088924611>

翻译是不是有间隔时间吗 。打开不同页面，不能立刻翻译吗！
[image: @yangchen158158] <https://github.com/yangchen158158>

Author
yangchen158158 <https://github.com/yangchen158158> commented 2 minutes ago
<https://github.com/chunibyocola/sc-translator-crx/issues/41#issuecomment-1088926438>

就油管翻译有问题， 别的页面都正常。 设置的翻译快捷键ALT+F。 快捷键一按就翻译出来了。

sweetcola ***@***.***> 于2022年4月5日周二 22:59写道：

**Comment by yangchen158158** [comment]
[image: image.png][image: image.png][image: image.png]
[image: image.png][image: image.png]   最下面个 播放按钮。灰色。不能点击翻译的。

杨谦 ***@***.***> 于2022年4月6日周三 00:02写道：

**Comment by yangchen158158** [comment]
[image: image.png]  这个对话框可以去掉吗。每次按 翻译快捷键ALT+F。 都是这个按一下，弹出来
，再按一下关闭。但是就是不翻译成功。

杨谦 ***@***.***> 于2022年4月6日周三 00:05写道：

**Comment by yangchen158158** [comment]
[image: image.png]     油管 换个页面然后要切换一个翻译源 才能点击开始网页翻译按钮  不切换的话，按钮是灰色
点击没反应，切换一下 就变黑 ，可以点翻译了

杨谦 ***@***.***> 于2022年4月6日周三 00:11写道：

**Comment by chunibyocola** [comment]
你在邮件中回复我是看不到图片的。

> [image: image.png]  这个对话框可以去掉吗。每次按 翻译快捷键ALT+F。 都是这个按一下，弹出来
，再按一下关闭。但是就是不翻译成功。

我猜你在说让控制栏不显示，可以先启用“激活网页翻译后直接翻译”选项后再启用“首次激活时不显示控制栏“。至于网页翻译失败的问题，我已经测试过了，是没有问题的。你在油管中翻译失败大概率跟浏览器相关，

> [image: image.png]     油管 换个页面然后要切换一个翻译源 才能点击开始网页翻译按钮  不切换的话，按钮是灰色
点击没反应，切换一下 就变黑 ，可以点翻译了

这个使用请直接点关闭按钮，然后再次激活网页翻译，无需切换翻译源。

已经知道不是功能上有 bug ，所以这个 issue 我就先关闭了。
