### ISSUE TITLE
网页翻译建议

### ISSUE THREAD

**Issue by guzzhao** [chunibyocola/sc-translator-crx#44]
非常好用的拓展😊,有下面建议
1. 这个页面举例`https://www.npmjs.com/package/jotai`,有一些不用翻译,比如版本号(全数字),代码片段.
2. 对照翻译翻译后的文本增加一个标识,比如一个虚线框.
3. 点击拓展图标弹出框添加网页翻译按钮

**Comment by chunibyocola** [comment]
> 这个页面举例https://www.npmjs.com/package/jotai,有一些不用翻译,比如版本号(全数字),代码片段.

检测全数字就会造成对所有文本片段进行检测，并且在格式方面也不好处理，所以选择保留了 Chrome 和 Edge 的做法。代码片段是因为 npm 不使用 code 标签进行包裹，用 pre + class name 进行标记的方法并不全面，也可能会造成一些地方的漏译，因此不作特殊处理。

> 对照翻译翻译后的文本增加一个标识,比如一个虚线框.

已经有这样的计划了，会像“插入翻译结果”那样在下方加入蓝色划线。

> 点击拓展图标弹出框添加网页翻译按钮

因为已经有快捷键和右键菜单可以激活网页翻译了，加一个按钮的话感觉是不如直接使用这两种方法，而且在新版本中会加入两个新按钮，会显得比较拥挤。

**Comment by guzzhao** [comment]
https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations
用`pre`的情况还不少

**Comment by chunibyocola** [comment]
你可以看到在那里面是`<div class='hightlight><pre /></div>`。是一个和 npm 不同的格式，别的网站也会不一样，甚至可能连 hightlight 的 class 都没有。直接把 pre 给忽略掉的话在一些新闻网站又会导致漏译。

当然你可以使用脚本给这些元素加上`notranslate` class 来让网页翻译忽略。比如在`https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations`里你可以直接在控制台里输入
```JavaScript
document.querySelectorAll('.highlight').forEach(v => v.className += ' notranslate')
```
。

**Comment by chunibyocola** [comment]
对照模式下已在译文下方加入下划线用以区分。

经过思考后决定暂时不会在弹出页中添加网页翻译按钮（已有右键菜单和快捷键可以激活网页翻译，没有必要增加更多的网页翻译入口），因此会关闭此 issue。

感谢反馈！
