### ISSUE TITLE
网页翻译双文对照排版问题，以及个人建议

### ISSUE THREAD

**Issue by Charlie-lies** [chunibyocola/sc-translator-crx#45]
你好，我是edge浏览器用户。我在使用网页翻译，选择显示原文+译文的时候，出现网页上部分结果中英文排版“混乱”的情况。
例如以下网站。这种“混乱”是因为HTML源码本身把一段句子分割在不同标签内了，才导致翻译结果不是期望的那样。我目前用划词翻译+自动把翻译结果插入网页的功能临时代替使用。
 请问会有更好解决的方法吗？谢谢！<br />
https://docs.microsoft.com/en-us/powerquery-m/m-spec-lexical-structure
<br />

![双文对照翻译结果](https://user-images.githubusercontent.com/53304920/163701027-e22c2f4b-8b7a-4782-86bf-330ee3238c19.PNG)

![双文对照翻译结果-htlm源码](https://user-images.githubusercontent.com/53304920/163701099-e35c9da6-998c-4ac5-a0d5-6452e3b6f026.PNG)

<br /><br />
另外有一个功能上的建议。是否考虑网页翻译结果显示译文时，支持鼠标悬停显示原文。或者反之结果显示原文，鼠标悬停显示译文。我之前用过这样的一个翻译插件（貌似是某款浏览器自带的？），但是之前用的电脑坏了。已经找不到了。一直没找到替代的插件。SC是我目前最满意的翻译插件了。

**Comment by chunibyocola** [comment]
> 这种“混乱”是因为HTML源码本身把一段句子分割在不同标签内了，才导致翻译结果不是期望的那样。我目前用划词翻译+自动把翻译结果插入网页的功能临时代替使用。

这是符合预期的，像 Chrome 和 Edge 自带的的网页翻译也是这样的。之后会在`原文 + 译文`状态的时候给译文加上下划线来让用户更好地识别译文。

> 另外有一个功能上的建议。是否考虑网页翻译结果显示译文时，支持鼠标悬停显示原文。或者反之结果显示原文，鼠标悬停显示译文。

技术上是能做到的，只是不清楚是否有这个必要，毕竟有`原文 + 译文`我感觉是比悬浮体验还要好的。我会权衡一下的。

> SC是我目前最满意的翻译插件了。

谢谢支持！

**Comment by guzzhao** [comment]
![1](https://user-images.githubusercontent.com/17945982/163941325-e1283100-c3bc-40c3-90c0-5a2b12944709.png)
![2](https://user-images.githubusercontent.com/17945982/163941340-3e82ec80-53a5-4dfb-a295-91509d4a8a96.png)
可以参考彩云的拓展

**Comment by chunibyocola** [comment]
这是两种完全不同的方式，在一些页面中这种方式会导致页面混乱。我不知道彩云在只显示译文的时候能不能让文本中的链接保持可点击的状态，我没试过但根据你的截图我推测是不能的。

**Comment by chunibyocola** [comment]
在“原文”模式下的“鼠标悬停在原文上时显示译文”、“原文 + 译文”模式下的“将下划线添加到译文”、“译文”模式下的“鼠标悬停在译文上时显示原文”都已开发完成。启用时需要在选项页面中的`网页翻译 -> 增强展示`选中后启用。

以上功能将会在 v4.1.0 上启用。

感谢建议。
