### ISSUE TITLE
右键菜单，翻译当前页面，为什么浏览器重启一下，菜单就不见了。

### ISSUE THREAD

**Issue by 8267020** [chunibyocola/sc-translator-crx#46]
添加右键菜单 翻译当前页面，使用起来方便。但是为什么重启以后，菜单就没有这个功能了。检查设置里面，还在选中状态。
在EDGE上测试。

**Comment by chunibyocola** [comment]
在我这里怎么试都不会发生这种问题，无论是更新还是重新安装。然后我想到有一种可能性就是你下载的扩展里有使用了相同 ID 的右键菜单。我试了一下发现确实是会发生这种问题。

你是同时安装了那个“超级翻译”吗？如果是的话请尽快卸载掉，那个是一个克隆可可翻译的恶意扩展，里面有侵犯用户隐私的代码。

**Comment by 8267020** [comment]
我是在edge 插件商店，下载的这个超级翻译，  这应该不是假冒的吧，如果是假冒的，我去哪里下载你的扩展呢？
详细信息
版本2.0.14
已更新 2022年4月28日

**Comment by 8267020** [comment]
找到了，你的页面下面有下载地址，叫可可翻译 

太可恶了下载到假冒的插件了！

**Comment by chunibyocola** [comment]
微软扩展商店的审核可以说是十分不过关，你搜索的前十个有六个都是这种恶意扩展。这个恶意扩展甚至还是排头位，十分无语。

**Comment by 8267020** [comment]
已经下载你你的正版，可可翻译。  我要去举报那个扩展。希望大佬能在自己的网址放一个crx文件，方便某些浏览器使用！

非常感谢！

**Comment by chunibyocola** [comment]
https://www.crx4chrome.com/extensions/icfnljfpacimpcbpammmbclmhenimhfc/

如果需要 CRX 文件的话你可以在上方的网址处下载，我没试过是否可靠。然后是因为使用了 MV3，要版本号大于 88 的基于 Chromium 的浏览器才能使用。

**Comment by 8267020** [comment]
谢谢您的热心帮助，已经想办法在chrome商店下载了！
