### ISSUE TITLE
Firefox 下，重启浏览器会导致右键菜单消失

### ISSUE THREAD

**Issue by oott123** [chunibyocola/sc-translator-crx#47]
sc: 4.1.0

firefox: 100.0.2 (64-bit)

windows: win11 21H2 22000.675

现象：每次启动 Firefox 浏览器，网页右键菜单中不会有 sctranslator 的选项，需要打开设置，重新取消勾选，再勾选一次，才可以看到右键菜单

**Comment by chunibyocola** [comment]
已确认问题，似乎是 Firefox 每一次关闭浏览器都会清空扩展的右键菜单，我会发布一个 v4.1.1 来尝试修复这个问题。

**Comment by chunibyocola** [comment]
已更新至 v4.1.1，在 about:addons 页面里点击设置按钮里的检查更新即可更新到 v4.1.1。

感谢你的反馈！

**Comment by oott123** [comment]
在我这边看也确认已经修复了，谢谢！
