### ISSUE TITLE
[功能请求]增加一个自动网页翻译选项

### ISSUE THREAD

**Issue by FQtianlan** [chunibyocola/sc-translator-crx#49]
**功能请求：**增加一个自动网页翻译选项
 - ![image](https://user-images.githubusercontent.com/76417073/174263037-792187da-0af6-4a20-9a4b-4f2ffebb38ba.png)

**实现建议：**通过html标签 lang属性判断

- ![image](https://user-images.githubusercontent.com/76417073/174262642-3fd00e19-840a-47d3-be22-65f5b61b1c55.png)

**Comment by FQtianlan** [comment]
另外 在本地文件网页中 网页翻译似乎无效
已经开启 “允许访问文件网址”选项

**Comment by chunibyocola** [comment]
Duplicate of #27

> 这个要实现还是比较简单的，但是目前的网页翻译算法还没有实装监听元素变化的功能，不能像原生谷歌网页翻译那样有新内容就翻译新内容。
>
> 所以就会导致有可能只翻译了一小部分内容（其它的并没有在翻译前加载），之后需要用户关闭翻译再启动翻译。所以这个功能需要等我实装了监听元素变化的算法之后才会去增加。
>
> 这个算法我已经是想好怎么写了，但我不确定我是否应该这样做，因为实装之后是有可能会产生频繁请求接口的现象（这也是谷歌和微软目前的做法，虽然发生的概率会很低但就是会发生）。

目前，我决定暂时不考虑“自动网页翻译”这个需求了，我的目的不是去替代浏览器自带的网页翻译，而是在某种情况下加强。而且，网页翻译可以通过使用快捷键就能简单触发。

> 另外 在本地文件网页中 网页翻译功能无效
> 已经开启 “允许访问文件网址”选项

目前没有为 content-script 匹配本地文件，下个版本会加上的。

**Comment by chunibyocola** [comment]
> 目前没有为 content-script 匹配本地文件，下个版本会加上的。

我尝试了一下，发现不行。在链接文件阶段会报错`net::ERR_BLOCKED_BY_CLIENT`。

我尝试用 MV2 标准去匹配本地文件，发现是可行的，也就是意味着这很可能是一个 MV3 才有的 Bug 。也就是说这个需求目前来说是完成不了的，需要等待 Chromiun 团队去修复这个问题。所以现在先关闭 issue 。

感谢你提出的建议。
