### ISSUE TITLE
我发现火狐和edge浏览器同样的页面，火狐浏览器没有触发翻译

### ISSUE THREAD

**Issue by ccvbc** [chunibyocola/sc-translator-crx#53]
设置是一样的,这可能算一点小意外，其他网页还是很好，仅供参考
目标网页地址：https://addons.mozilla.org/zh-CN/firefox/addon/traduzir-paginas-web/reviews/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org
演示图如下
![image](https://user-images.githubusercontent.com/103726582/177023106-13017ec0-f7c7-4847-82f3-9098c7a72aa6.png)
![image](https://user-images.githubusercontent.com/103726582/177023123-7d90476d-eeb9-4801-a274-26de77fc3ee3.png)
edge设置
![image](https://user-images.githubusercontent.com/103726582/177023233-0036a178-1161-49b0-a487-ff6278a86e93.png)
![image](https://user-images.githubusercontent.com/103726582/177023253-05a4395d-3083-42e7-aa14-589cf8eb733f.png)
火狐设置
![image](https://user-images.githubusercontent.com/103726582/177023285-4692aec7-ce53-4b9b-aa6e-e0d169536741.png)
![image](https://user-images.githubusercontent.com/103726582/177023287-4aa4456a-cf97-49fc-9e16-ed56c6b6d724.png)

**Comment by chunibyocola** [comment]
这是正常的，在 Firefox 浏览器里应该有内部设置在 `addons.mozilla.org` 域名的网页里不允许扩展内容嵌入。反之在 Edge 浏览器的 Edge 商店里也同样不可以。

**Comment by ccvbc** [comment]
好嘞懂了
