### ISSUE TITLE
希望允许添加“在独立窗口中翻译剪贴板内容”的快捷键

### ISSUE THREAD

**Issue by QyhOfficial** [chunibyocola/sc-translator-crx#57]
这样可以配合其他软件实现浏览器外翻译

**Comment by chunibyocola** [comment]
之后会在“独立翻译窗口”下加入一个新的选项“使用‘打开独立翻译窗口’快捷键时自动读取剪贴板”或者在使用“打开独立翻译窗口”快捷键后自动读取。

**Comment by QyhOfficial** [comment]
好的。目前已有的“打开弹出页面或独立翻译窗口时，最后的剪贴板文本将自动粘贴到输入框中”功能的问题是，如果独立窗口已经打开，再次按下“打开独立窗口”的快捷键就不会重新读取剪贴板内容。您这种方案也可以解决这个问题。

**Comment by chunibyocola** [comment]
现在，在“自动粘贴到输入框中”已启用的情况下，使用“打开独立翻译窗口”快捷键将会自动翻译剪贴板中的文本。

这一功能将会在下个版本 v4.3.0 中可用。

感谢你的建议。
