### ISSUE TITLE
关于收藏列表的一键导出和增加翻译源及笔记

### ISSUE THREAD

**Issue by liuguanqiu** [chunibyocola/sc-translator-crx#58]
您好！贵app的收藏功能，我个人觉得非常棒！希望能在已有基础收藏功能上，把它改为一个类似笔记本的功能，具体需求如下：
1、能够一键导出收藏列表的所有内容（包括中英文翻译、原文链接、笔记、标签）
2、能够给每条收藏加上自定义分类标签
3、收藏内容能够链接到原网页（或文件出处），一键点击直达
4、能够对于收藏内容进行补充的笔记编辑（添加批注文本等，约等于可以直接修改收藏列表内的中英文内容（目前只能阅读，不能修改））

如果能够做到以上这些，相信会是一个特别棒的进步！尤其对需要经常阅读和做笔记的科研人员和工作党而言。感谢！

**Comment by chunibyocola** [comment]
目前有新的增加收藏页面功能的计划，具体如下：

1. 添加笔记

用户可以在收藏页中为选择的收藏项添加笔记。

2. 添加标签

程序内不预设标签，需要用户自己填写。

新标签被添加到收藏项后可以在“所有标签”找到。

如果标签不被所有收藏项引用则会被自动删除。
