### ISSUE TITLE
显示控制栏

### ISSUE THREAD

**Issue by Sunrongguo2008** [chunibyocola/sc-translator-crx#65]
显示控制栏

**Comment by chunibyocola** [comment]
请补充更多描述

**Comment by Sunrongguo2008** [comment]
如何打开网页时自动显示控制栏？
![image](https://user-images.githubusercontent.com/91547012/192124581-670868ad-4723-40cb-972c-6e7a064bb00c.png)

**Comment by chunibyocola** [comment]
此功能尚未被支持，就算开发出来，用户大概也不会去启用，因为通常不会以外文网站作为自己的主要浏览对象，这时这个功能就不应该被启用。而且目前有很多方法都能激活网页翻译（显示控制栏），比如快捷键。再就是下个版本会加入面向域名的自动翻译，与“打开网页时自动显示控制栏”有非常大的重合空间。

所以这个 issue 我就先关闭了。
