### ISSUE TITLE
手机上怎么翻译网页？

### ISSUE THREAD

**Issue by 2584191127** [chunibyocola/sc-translator-crx#68]
我在kiwi上安装了这个插件，手机上不能使用快捷键也没有右键，所以要怎么翻译网页呢

**Comment by chunibyocola** [comment]
抱歉，这个我帮不了你，因为这个插件本身是不支持手机的，我也没有使用过 KIWI 这个浏览器😂，也没有在与其相关的商店上架过。

**Comment by 2584191127** [comment]
> 抱歉，这个我帮不了你，因为这个插件本身是不支持手机的（没有考虑过在手机上的运行），我也没有使用过 KIWI 这个浏览器joy，也没有在与其相关的商店上架过。

kiwi浏览器支持Chrome Web Store，可以考虑加一个功能吗：点击扩展翻译网页

**Comment by chunibyocola** [comment]
> kiwi浏览器支持Chrome Web Store，可以考虑加一个功能吗：点击扩展翻译网页

现在的情况是扩展面向的是桌面端浏览器，而对于这方面的用户来说，激活网页翻译的方法已经足够多了，增加更多的入口不一定是一件好事。

不过之前也有用户提出过类似的需求，我考虑一下吧。
