### ISSUE TITLE
Google网页翻译不可用。

### ISSUE THREAD

**Issue by Readon** [chunibyocola/sc-translator-crx#69]
应该是由于google翻译国内链接取消的原因。

**Comment by chunibyocola** [comment]
是的，目前大陆用户可以通过添加新的 hosts 规则的方法来临时修复这个问题，比如：
```
180.163.151.162 translate.googleapis.com
```
我这边是无法通过程序做任何修复的。

**Comment by Readon** [comment]
如果能够允许使用代理也可以接受。

**Comment by chunibyocola** [comment]
当然是可以的，只需要自行添加规则。

也可以使用 Microsoft 网页翻译源进行代替。

**Comment by Readon** [comment]
如果要按效果排序的话，翻译还是DeepL>>>Google>微软。
