### ISSUE TITLE
the default height could be adaptive？

### ISSUE THREAD

**Issue by jayteen** [chunibyocola/sc-translator-crx#7]

**Comment by chunibyocola** [comment]
I don't know what you mean exactly.

Could you please provide more information?

**Comment by jayteen** [comment]
> I don't know what you mean exactly.
> 
> Could you please provide more information?

![image](https://user-images.githubusercontent.com/62333772/119621835-29491200-be39-11eb-9ef3-ca273050cce6.png)
The default height of the translation panel is like this. I remember it didn't look like this when I first installed it, but it's like this now. It's hard to open this way and look at the blank below. What's the reason. By the way, this translation plug-in is very useful

**Comment by chunibyocola** [comment]
Yes, it was before.

You can notice that the language selection is changed and get more functions like `language query` and `recent language`. To implement this, I can't use the native HTML tag `select`. And I need to display more language by adding blank.

It is a compromise. 😂

**Comment by jayteen** [comment]
Do you mean the two language choices below. It is just such a height to open. Is that the case.
So it was intentional, right? I thought it was my browser problem. Okay, thank you, big guy.

**Comment by jayteen** [comment]
Is it possible to make it so high when clicking? Actually, I don't quite understand the principle

**Comment by chunibyocola** [comment]
Yes, it is possible. But I think the blank suddenly appear or disappear don't look beautiful.
