### ISSUE TITLE
一个微小的问题：可可翻译 for Firefox 不显示图标

### ISSUE THREAD

**Issue by elviscai** [chunibyocola/sc-translator-crx#70]
一个微小的问题：可可翻译 for Firefox 在 Hacker News（https://news.ycombinator.com/ ）上开启网页翻译后不显示图标。
尝试清除数据重装扩展仍未解决。
macOS 11.7 Firefox 102

**Comment by chunibyocola** [comment]
打开控制栏可以看见一个报错是：

> Content Security Policy: 页面设置阻止读取位于 data:image/png;base64,iVBORw0KGgoAAAANSU… 的一项资源("img-src")。

这个问题是 [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) 的问题，这也是无法解决的。同时我注意到的一点是这个网站对待 html 标签的方式也很“独特”，让长度可超出屏幕，导致一些功能（菜单处于屏幕范围内、翻译面板处于屏幕范围内）的失效。
