### ISSUE TITLE
openkylin 360浏览器 右键菜单不出来

### ISSUE THREAD

**Issue by windyslove** [chunibyocola/sc-translator-crx#72]
openkylin 360浏览器刚打开的时候，右键菜单不出来，进入选项随便勾一下右键菜单选项一下然后才出来

**Comment by chunibyocola** [comment]
一般来说，如果是基于 Chromium 的浏览器，是不会有这个问题的，既然是成功安装的话那版本至少是大于 88 的。还有可能你安装的并不是我所提供的版本，而是安装了一些“山寨”版本，在这些“山寨”版本中我知道会存在这样的 BUG。

并且你的这个环境我是无法去测试重现的，也并非我所上架的 3 个浏览器中的一个。很抱歉无法帮助到你。
