### ISSUE TITLE
可以像TWP插件一样在右上弹出吗，而且鼠标单击网页希望翻译消失，不然每次要先关闭才能翻译下一段。

### ISSUE THREAD

**Issue by AlexSameeei** [chunibyocola/sc-translator-crx#73]

**Comment by chunibyocola** [comment]
描述有点混乱，不能完全明白你所想表达的意思。

想要隐藏控制栏的话可以在选项里设置。

> 不然每次要先关闭才能翻译下一段

有两个新功能都是针对这个问题的，分别是控制栏中的“重新开始网页翻译”和选项页中的“翻译动态生成的内容
”选项。

**Comment by AlexSameeei** [comment]
意思是 我选择一个单词翻译会弹出一个对话框，我再次选一个词进行翻译会跳出第二个框，请问我应该如何设置才能，只出现一个框。我的使用场景是在火狐浏览器打开了一个PDF用您的插件进行翻译，如图所示，我不想出现那么多的框



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月21日(周五) 中午11:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chunibyocola/sc-translator-crx] 可以像TWP插件一样在右上弹出吗，而且鼠标单击网页希望翻译消失，不然每次要先关闭才能翻译下一段。 (Issue #73)




 
描述有点混乱，不能完全明白你所想表达的意思。
 
想要隐藏控制栏的话可以在选项里设置。
  
不然每次要先关闭才能翻译下一段
  
有两个新功能都是针对这个问题的，分别是控制栏中的“重新开始网页翻译”和选项页中的“翻译动态生成的内容
 ”选项。

**Comment by chunibyocola** [comment]
我测试了一下发现还真的是这样，看来这是一个当前版本在 Firefox 独有的一个 bug，在其他浏览器运作正常，我看看能不能修复。

**Comment by AlexSameeei** [comment]
嗯嗯，谢谢你的回复，另外右键翻译网页，右下角会弹出开始翻译按钮。这样是不是有点多次一举，很棒的插件。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月21日(周五) 中午11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chunibyocola/sc-translator-crx] 可以像TWP插件一样在右上弹出吗，而且鼠标单击网页希望翻译消失，不然每次要先关闭才能翻译下一段。 (Issue #73)




 
我测试了一下发现还真的是这样，看来这是一个当前版本在 Firefox 独有的一个 bug，在其他浏览器运作正常，我看看能不能修复。

**Comment by chunibyocola** [comment]
可以启用“激活网页翻译后直接翻译”选项来跳过点击的步骤，没有默认启动此选项是考虑到用户可能会先选择翻译源或者目标语言，从而造成无用的翻译请求。

**Comment by chunibyocola** [comment]
在 Firefox 扩展商店中已经更新到 v4.5.1，修复独立翻译窗口可以被重复创建的问题。主动更新一下这个问题就会被修复了。

感谢你提出的问题。

**Comment by AlexSameeei** [comment]
你好，谷歌翻译引擎不能用了，有办法解决吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月21日(周五) 中午12:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chunibyocola/sc-translator-crx] 可以像TWP插件一样在右上弹出吗，而且鼠标单击网页希望翻译消失，不然每次要先关闭才能翻译下一段。 (Issue #73)




 
Closed #73 as completed.

**Comment by chunibyocola** [comment]
谷歌翻译并没有失效，只是谷歌不在大陆地区提供服务了。目前只能通过 hosts（不稳定）或者代理来使用谷歌翻译。

**Comment by AlexSameeei** [comment]
👌🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月1日(周二) 下午4:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chunibyocola/sc-translator-crx] 可以像TWP插件一样在右上弹出吗，而且鼠标单击网页希望翻译消失，不然每次要先关闭才能翻译下一段。 (Issue #73)




 
谷歌翻译并没有失效，只是谷歌不在大陆地区提供服务了。目前只能通过 hosts（不稳定）或者代理来使用谷歌翻译。
