### ISSUE TITLE
希望增加火山翻译，腾讯翻译等

### ISSUE THREAD

**Issue by mydracula** [chunibyocola/sc-translator-crx#74]
主要用网页全文翻译建议新增右键菜单而不是点图标全文翻译主要不方便

目前支持谷歌和微软

自定义网页翻译源实在是看不懂怎么设置

希望能增加像划词翻译一样的还想要其他的翻译

![](https://m.360buyimg.com/babel/jfs/t1/213049/28/22591/125778/63522bf6Ed22d347b/2f3a1617bac5cb0d.png)

**Comment by chunibyocola** [comment]
火山翻译我自己试用了一下似乎和其他的差不多。腾讯翻译我以前试过似乎是有 host 锁，并且语言不互通。试用了一下官方的网页翻译，质量较差。之前我也想过加入 Yandex 的网页翻译，同样是翻译质量的问题所以没有继续下去。

> 主要用网页全文翻译建议新增右键菜单而不是点图标全文翻译主要不方便

已支持，在选项页中的“右键菜单”栏目中勾选即可。

> 自定义网页翻译源实在是看不懂怎么设置

自定义网页翻译源需要一定的后端知识，剩下的只是 API 的规范。

增加新的翻译源不是目前的主要目标。目前没有想法去增加翻译能力没有与已经自带的拉开太大差距的翻译源，像 DeepL 的话在 MV3 规范下无法去增加。
