### ISSUE TITLE
浏览器右上角的扩展图标左键单击时可以直接翻译网页

### ISSUE THREAD

**Issue by jssys523** [chunibyocola/sc-translator-crx#75]
目前浏览器右上角的扩展图标左键单击时弹出翻译面板，希望可以在设置里面可以选择左键单击扩展图标采取的操作，比如弹出翻译面板或者翻译整个页面，这样频繁使用网页翻译就可以经过设置后一键翻译网页了，十分感谢~

**Comment by chunibyocola** [comment]
跟这个功能相关的问题我考虑挺久了，目前应该不会去实现这个功能。不过会做一个类似的功能：
- 在弹出页中增加一个“激活网页翻译”的图标
- 点击此图标后会在当前页面激活网页翻译（如果允许插入脚本的话）
- 此时这个图片会变为“结束网页翻译”图片
- 点击此图标后结束网页翻译

虽然这个功能比起你所说的一键激活要多一个步骤，但这个步骤我觉得是更加清晰的。虽然感觉和使用右键菜单没什么区别，也算是增加更多的网页翻译入口吧。

**Comment by jssys523** [comment]
感谢您的回复~
我是这样认为的，浏览器中遇到的单词或者句子，大部分是通过选中后弹出的小图标来快速翻译，很少去点击右上角的扩展图标来输入查询，目前网页翻译我是使用右键来进行翻译，需要2步，由于右键中还有其他的很多扩展选项，所以要寻找一下才能看到，恰好我在尝试多个翻译扩展时，Imtranslator中有一项设置是：

这个设置就是可以自定义右上角的扩展按钮左键单击的默认操作，这一点我觉得是很值得参考的，之前我在使用官方谷歌翻译扩展时，翻译一个网页需要点击下扩展图标，再点击弹出窗口的翻译此界面：

就总感觉2步不够方便，因为在持续浏览多个英文网页时，会频繁使用翻译，一键确实会体验很好。可以添加一个设置单击入口，只需要点击一下即可，关闭翻译也不需要点击上面，因为右下角会有切换翻译的那个小工具，可以关闭翻译的。
您说的想法我觉得和这个优化不冲突的，只是单击入口一个是侧重查询单词，一个侧重翻译网页。
双语对照翻译网页确实是一个很棒的功能，再次感谢您的回复，祝您身体健康，一切顺心。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chunibyocola/sc-translator-crx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chunibyocola/sc-translator-crx] 浏览器右上角的扩展图标左键单击时可以直接翻译网页 (Issue #75)





 
跟这个功能相关的问题我考虑挺久了，目前应该不会去实现这个功能。不过会做一个类似的功能：
  
在弹出页中增加一个“激活网页翻译”的图标
 
点击此图标后会在当前页面激活网页翻译（如果允许插入脚本的话）
 
此时这个图片会变为“结束网页翻译”图片
 
点击此图标后结束网页翻译
  
虽然这个功能比起你所说的一键激活要多一个步骤，但这个步骤我觉得是更加清晰的。虽然感觉和使用右键菜单没什么区别，也算是增加更多的网页翻译入口吧。

**Comment by chunibyocola** [comment]
感谢支持。

一键激活的方法倒是有的，可以通过使用快捷键的方式直接激活。针对右键菜单中栏目过多，可以右键扩展图标，在菜单里也有”激活网页翻译“的栏目。

更加全面去考虑的话就是有一些问题不能解决，比如一个“启用了点击图标激活网页翻译的用户在需要快捷翻译一些剪贴板中的文本，他们必须做更多的操作”。所以经常使用网页翻译的用户我觉得使用快捷键就能完美覆盖了，这是我的想法。

**Comment by jssys523** [comment]
感谢您的回复，我设置一下快捷键一键翻译，这样也方便的
