### ISSUE TITLE
剪切板

### ISSUE THREAD

**Issue by nannanzhao** [chunibyocola/sc-translator-crx#78]
剪切板打开时默认大小希望可以调整

**Comment by chunibyocola** [comment]
"剪切板"指的是什么？麻烦补充更多说明。

**Comment by nannanzhao** [comment]
现在是这样显示的
![image](https://user-images.githubusercontent.com/6504958/197927162-f520dd09-012f-48bd-9c09-a7b0bf23ab0c.png)

希望可以这样显示
![image](https://user-images.githubusercontent.com/6504958/197927254-5a463dd7-b5b1-4f12-80e9-5538746e95fc.png)

**Comment by chunibyocola** [comment]
可以的，把下面代码复制粘贴到：主题 -> 自定义样式框
```CSS
.raw-text__textarea { height: 100px; }
```
就可以把默认高度设置为 100px，你也可以把 100 替换成其他数字，最大为 150。

**Comment by nannanzhao** [comment]
嗯嗯，好的，非常感谢！

**Comment by chunibyocola** [comment]
不客气。
