### ISSUE TITLE
最近谷歌翻译用不了了，可以修改插件的ip嚒

### ISSUE THREAD

**Issue by sbkk000** [chunibyocola/sc-translator-crx#79]
最近谷歌翻译用不了了，可以修改插件的ip嚒。用translate.googleapis.com 解析国内ip 然后修改插件激活谷歌翻译吗

**Comment by chunibyocola** [comment]
插件无法更改域名的解析，这是非常不安全的。

> 最近谷歌翻译用不了了

在 issue #69 中有用户方面如何应对这种情况的解决方案，我是无法通过插件来解决这个问题的，抱歉。
