### ISSUE TITLE
希望添加一个网页翻译快捷键 在:1.原文[关闭翻译] 2.原文 + 译文 3.译文 之间切换

### ISSUE THREAD

**Issue by 1208041822** [chunibyocola/sc-translator-crx#89]
希望添加一个网页翻译快捷键 在:1.原文[关闭翻译] 2.原文 + 译文 3.译文 之间切换
I want to add a webpage translation shortcut key to switch between: 1. Original [translation off] 2. Original + translation 3. Translation

**Comment by chunibyocola** [comment]
已经有了，“切换网页内网页翻译结果的显示方式”快捷键就是你所说的这个功能。

**Comment by 1208041822** [comment]
可能我没太表述清楚 我的意思 现在需要先激活"翻译当前界面"功能 然后才能单独按快捷键来切换这三个状态
我想要的是 直接按一个键 直接激活翻译功能 然后再次按这个键 可以切换这三个状态

**Comment by chunibyocola** [comment]
这样不适合，一个快捷键不应该承担多种功能。

**Comment by 1208041822** [comment]
嗯..我觉得一个快捷键来切换开关状态很适合吧 隔壁的TWP - Translate Web Pages就是这么做的 我想从它这个完全转到可可翻译就是差在这个功能上了 或者不必三种状态切换 两种也行 就是译文和原文之间用一个快捷键来控制

**Comment by 1208041822** [comment]
"翻译当前页面" 快捷键 现在只能按一次开启 想关闭只能用鼠标操作 设置"再按一次关闭"是否更符合操作逻辑
