### ISSUE TITLE
关于本浏览器扩展对移动端（Android/iOS）浏览器的支持bug问题

### ISSUE THREAD

**Issue by dongzide** [chunibyocola/sc-translator-crx#90]
这是我用过的最棒的网页翻译浏览器扩展，自定义功能超强。但目前它只支持桌面端浏览器（windows/Linux/MacOS 下的 Chrome/Edge/Firefox），我尝试把本扩展安装到移动端（Android/iOS）浏览器，结果出现一些问题。

目前我调研到的”把Chrome浏览器扩展安装到移动端浏览器“的最简单方法为：

## Android

**Kiwi/Yandex/狐猴浏览器(国产)** 等Android版浏览器（Webkit/Blink内核）都支持直接安装Chrom或Edge市场的扩展，但由于这些扩展都是为桌面版环境开发的，在Android手机浏览器下安装后不一定能正常使用（只有一部分扩展可用）。

遗憾的是 可可翻译 安装后就不能正常使用。
我用 狐猴浏览器 在Chrome扩展市场安装了本扩展。只有点击扩展图标输入文本翻译功能可用，网页界面内的操作都失效。例如选中文本不会自动弹出翻译按钮。
**最重要的网页全文翻译功能，因为手机浏览器无法右键，所以调不出网页翻译控制栏也就没法翻译网页了。**

**我建议在扩展popup界面增加个”网页翻译“按钮，不需要右键激活网页翻译，点击扩展界面的按钮就能激活网页全文翻译**。
当然，其他网页内功能（如划词翻译）也可以设法兼容一下。

（我测试其他chrome翻译扩展，如：Immersive Translate，Google翻译，网页翻译都可以正常使用，因为他们都有一个点击翻译的按钮。不过他们的翻译功能比较简陋）

## iOS

以前用于iPhone和iPad的iOS系统下浏览器不能安装扩展（苹果的限制）。现在出现一个新的iOS浏览器：

**Orion**，https://browser.kagi.com/

支持在iOS下安装任何Chrome和Edge扩展。这个浏览器开发者花了几年时间把70%通用Web扩展API（Chrome/Firefox扩展开发用的）移植到了苹果的WebKit平台。

**Orion浏览器对于本翻译扩展的支持程度我没有测试（猜测和Android下一样不能使用），作者可以试一试。**

---

如果本扩展能支持上述Android和iOS浏览器，那么它就成为目前唯一的全平台兼容翻译扩展了，可以在同时桌面端和移动端使用的翻译扩展，那就太厉害了。

**Comment by chunibyocola** [comment]
感谢使用与支持。

> 只有点击扩展图标输入文本翻译功能可用，网页界面内的操作都失效。例如选中文本不会自动弹出翻译按钮。

这大概是因为浏览器没有模仿鼠标的事件。不过我觉得这个功能对手机这个小屏幕不太友好，面板面积已经算小了，但估计还是会占了很多空间。

> 最重要的网页全文翻译功能，因为手机浏览器无法右键，所以调不出网页翻译控制栏也就没法翻译网页了。
>
> 我建议在扩展popup界面增加个”网页翻译“按钮，不需要右键激活网页翻译，点击扩展界面的按钮就能激活网页全文翻译。

这个按钮在 v4.6.0 中已经加入。

**Comment by dongzide** [comment]
> 感谢使用与支持。
> 
> > 只有点击扩展图标输入文本翻译功能可用，网页界面内的操作都失效。例如选中文本不会自动弹出翻译按钮。
> 
> 这大概是因为浏览器没有模仿鼠标的事件。不过我觉得这个功能对手机这个小屏幕不太友好，面板面积已经算小了，但估计还是会占了很多空间。
> 
> > 最重要的网页全文翻译功能，因为手机浏览器无法右键，所以调不出网页翻译控制栏也就没法翻译网页了。
> > 我建议在扩展popup界面增加个”网页翻译“按钮，不需要右键激活网页翻译，点击扩展界面的按钮就能激活网页全文翻译。
> 
> 这个按钮在 v4.6.0 中已经加入。

<img width="269" alt="截屏2022-11-13 上午10 00 48" src="https://user-images.githubusercontent.com/1448870/201502123-78dff8cc-6562-41e3-876c-a3075343b1e7.png">
我安装的就是chrome应用商店的最新版扩展，你说的网页翻译按钮在哪里？

**Comment by chunibyocola** [comment]
左上角这个就是，用的是跟 Edge 相同的翻译网页图标。

**Comment by dongzide** [comment]
> 左上角这个就是，用的是跟 Edge 相同的翻译网页图标。

还真有，如果你不说真的不知道这个字符居然是个按钮。
划词翻译功能移动端浏览器都自带，那这个扩展在android上就可用了。iOS上我没设备没试，应该也是可用的。

**Comment by dongzide** [comment]
> 感谢使用与支持。
> 
> > 只有点击扩展图标输入文本翻译功能可用，网页界面内的操作都失效。例如选中文本不会自动弹出翻译按钮。
> 
> 这大概是因为浏览器没有模仿鼠标的事件。不过我觉得这个功能对手机这个小屏幕不太友好，面板面积已经算小了，但估计还是会占了很多空间。
> 
> > 最重要的网页全文翻译功能，因为手机浏览器无法右键，所以调不出网页翻译控制栏也就没法翻译网页了。
> > 我建议在扩展popup界面增加个”网页翻译“按钮，不需要右键激活网页翻译，点击扩展界面的按钮就能激活网页全文翻译。
> 
> 这个按钮在 v4.6.0 中已经加入。

你说android下浏览器选中文本没有弹出翻译按钮可能是浏览器没有模仿鼠标事件，我用另一个类似功能的翻译扩展 https://github.com/immersive-translate/immersive-translate 发现它选中文本后可以弹出翻译按钮（尽管位置错位而且可能需要滑动下页面，但确实能显示翻译弹窗），那么可能不是没有模仿鼠标的问题。

有想解决下这个问题吗？我想它的既然可以选中文本弹出，你的扩展理论上不存在硬件或环境问题，应该也可以。

**Comment by chunibyocola** [comment]
确实是没有鼠标事件，因为手机端的事件是`touch`。我知道有一个叫做`selectionchange`的事件，但是没办法做到监听位置，也就是你说的

> 尽管位置错位而且可能需要滑动下页面，但确实能显示翻译弹窗

而且如果用户启用了“直接翻译”，那会直接导致发送 n (字数) 次请求，这是绝对不应该的。

我想想看有没有办法自己造一个桌面和手机都能完美运行的 `selectionend` 事件吧，但希望渺茫。

**Comment by dongzide** [comment]
> 

原来是这么回事，其实android下浏览器如chrome选中文本时都会默认弹出谷歌翻译按钮，无需扩展自带翻译，这点比桌面版浏览器方便，只是谷歌翻译国内被屏蔽了所以就难以推广到广大用户中了。

**Comment by dongzide** [comment]
> 确实是没有鼠标事件，因为手机端的事件是`touch`。我知道有一个叫做`selectionchange`的事件，但是没办法做到监听位置，也就是你说的
> 
> > 尽管位置错位而且可能需要滑动下页面，但确实能显示翻译弹窗
> 
> 而且如果用户启用了“直接翻译”，那会直接导致发送 n (字数) 次请求，这是绝对不应该的。
> 
> 我想想看有没有办法自己造一个桌面和手机都能完美运行的 `selectionend` 事件吧，但希望渺茫。

原来是这么回事，其实android下浏览器如chrome选中文本时都会默认弹出谷歌翻译按钮，无需扩展自带翻译，这点比桌面版浏览器方便，只是谷歌翻译国内被屏蔽了所以就难以推广到广大用户中了。
