### ISSUE TITLE
新增”切换网页翻译状态“快捷键

### ISSUE THREAD

**Issue by 1208041822** [chunibyocola/sc-translator-crx#91]
"翻译当前页面" 快捷键 目前只能控制开启 想要关闭只能用鼠标点击关闭按钮操作 
设置"再按一次关闭"是否更符合操作逻辑

**Comment by chunibyocola** [comment]
会加一个”切换网页翻译状态“快捷键，具体表现与目前在弹出页上的网页翻译切换键按钮一样：在扩展可用网页上使用此快捷键如果网页翻译未开启则直接开启网页翻译，如果网页翻译已开启则直接关闭网页翻译。

**Comment by 1208041822** [comment]
漂亮
