### ISSUE TITLE
本扩展网页翻译时将原文替换为3个 font 标签，他们分别是做什么用的呢？

### ISSUE THREAD

**Issue by dongzide** [chunibyocola/sc-translator-crx#94]
没发现文档，自己研究了下这个扩展。网页翻译时扩展将原网页文本替换为三个 font 元素。

* 第一个 font 元素，我猜是 原文。
* 第二个 font 元素，我猜是 译文。
* 第三个 font 元素，内容和第二个一模一样，且一直处于隐藏状态，它是做什么用的？

不知我猜的对不对？第三个font是起什么作用的呢？

**Comment by chunibyocola** [comment]
分别是原文、对照译文、译文。

**Comment by dongzide** [comment]
> 分别是原文、对照译文、译文。

对照译文和译文会同时出现在页面中吗？如果不同时出现的话有必要使用两个完全相同的元素吗?
