### ISSUE TITLE
网页翻译的‘原文加译文‘模式展示效果改进

### ISSUE THREAD

**Issue by xxnuo** [chunibyocola/sc-translator-crx#96]
### 网页翻译的‘原文加译文’模式中，‘非离散地展示译文’选项后，可以提供‘添加可选数量的换行符’选项，让译文展示并非紧跟原文后

**比如：**

![图片](https://user-images.githubusercontent.com/54252779/202592335-139b206c-d884-4e75-a1bb-94cdbe649082.png)

**和彩云小译对比：**

![图片](https://user-images.githubusercontent.com/54252779/202593148-17163a1b-d39f-4dc8-a824-0d09f8551540.png)

左图网址：[https://github.com/LGUG2Z/komorebi](https://github.com/LGUG2Z/komorebi)
右图网址：[https://interpreter.cyapi.cn/page/html/6376d99b84968be61616fb64](https://interpreter.cyapi.cn/page/html/6376d99b84968be61616fb64)

- _这里可以看到可可翻译有个BUG， `komorebi-application-specific-configuration` 这样的链接的文字彩云小译能正确翻译出来而可可翻译忽略了。_

- 右者在双语展示时译文展示并非紧跟原文后，看他的网页源码实现的方式是给每个文字添加了独特的类，可能照它的实现会比较困难。所以可以提供只加个换行符的功能就行，效果不完美但实现比较容易，而且效果也不会差太多😁

**Comment by chunibyocola** [comment]
> 网页翻译的‘原文加译文’模式中，‘非离散地展示译文’选项后，可以提供‘添加可选数量的换行符’选项，让译文展示并非紧跟原文后

不会这样做，这样做只会对正文有效，对其他地方比如 header, nav, menu 会是破坏性的变动。

> 右者在双语展示时译文展示并非紧跟原文后，看他的网页源码实现的方式是给每个文字添加了独特的类，可能照它的实现会比较困难。所以可以提供只加个换行符的功能就行，效果不完美但实现比较容易，而且效果也不会差太多😁

实现起来不难，它的做法是判断是否换行后决定是直接克隆元素对象还是在文本后加入。但这种做法我觉得算是一种妥协，因为它的翻译源我记得是不支持 XML 格式翻译，所以做不到在仅显示原文时保留文本格式（链接、字体格式等，而且这种方式造成页面样式混乱的概率是大于目前可可翻译使用的方式，这也是可可翻译决定不采用这种方式的关键因素。

> 这里可以看到可可翻译有个BUG， komorebi-application-specific-configuration 这样的链接的文字彩云小译能正确翻译出来而可可翻译忽略了。

放在 code 标签里的文本会被自动忽略，这种情况我是知道的，这算是设计的一种吧。确实看上去不太好看，我改为用双引号包括显示吧。

**Comment by Oeaps** [comment]
这个模式下翻译维基百科之类的容易出现bug，特别是段末有引用标签时
<img width="1244" alt="Snipaste_2022-11-26_16-45-27" src="https://user-images.githubusercontent.com/15799857/204080449-865a6818-9b2a-4551-84b4-5d32eb52045e.png">

**Comment by chunibyocola** [comment]
这种情况不算是 bug ，我试了一下，就算不使用这种模式，只要文本过长，在 `table.sidebar.sidebar-collapse.nomobile.nowraplinks.hlist` 里就是这样显示的。而采用非离散展示，在这种情况下就必然会造成文本过长，比如在一些使用内联元素来做子菜单的地方就会发生这种状况，这是用代码检测不出来的。

如果你是指段末有引用标签时译文也会变成引用标签的话，这同样不是 bug，这是必须的，因为这样做不会导致样式错乱，也不会造成翻译显示缺漏。

**Comment by Oeaps** [comment]
> 这种情况不算是 bug ，我试了一下，就算不使用这种模式，只要文本过长，在 `table.sidebar.sidebar-collapse.nomobile.nowraplinks.hlist` 里就是这样显示的。而采用非离散展示，在这种情况下就必然会造成文本过长，比如在一些使用内联元素来做子菜单的地方就会发生这种状况，这是用代码检测不出来的。
> 
> 如果你是指段末有引用标签时译文也会变成引用标签的话，这同样不是 bug，这是必须的，因为这样做不会导致样式错乱，也不会造成翻译显示缺漏。

好吧，主要是如果一个长段的段末是标签，译文会在同一行而且特别特别长，彩云小译那种排版会比较舒服
